/**
 * 
 */
package mx.gob.segob.nsjp.comun.enums.actuaciones;

import java.util.HashMap;
import java.util.Map;

/**
 * @author Jacob Lobaco
 * @deprecated
 *
 */
public enum Actuaciones {

    GENERAR_OFICIO_DE_SOLICITUD_DE_ATENCION_PSICOLOGICA_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(1L),
    SOLICITAR_ATENCION_PSICOLOGICA_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(2L),
    GENERAR_OFICIO_DE_SOLICITUD_DE_ATENCION_MEDICA_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(3L),
    SOLICITAR_ATENCION_MEDICA_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(4L),
    GENERAR_OFICIO_DE_SOLICITUD_DE_ASESORIA_JURIDICA_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(5L),
    SOLICITAR_ORIENTACION_LEGAL_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(6L),
    GENERAR_OFICIO_DE_SOLICITUD_DE_SEGURIDAD_POLICIAL_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(7L),
    SOLICITAR_SEGURIDAD_POLICIAL_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(8L),
    ADJUNTAR_ARCHIVO_DIGITAL(9L),
    GENERAR_DENUNCIA_ATP(10L),
    GENERAR_QUERELLA_ATP(11L),
    CAPTURAR_DECLARACION_ATP(12L),
    DIRIGIR_A_INSTANCIA_EXTERNA_ATP(13L),
    DIRIGIR_A_LA_UNIDAD_DE_SOLUCION_DE_CONTROVERSIAS_ATP(14L),
    DIRIGIR_A_LA_UNIDAD_DE_FISCALES_INVESTIGADORES_ATP(15L),
    AVISAR_QUE_LA_DENUNCIA_O_QUERELLA_SE_DIRIGIO_A_LA_UNIDAD_DE_MEDIOS_ALTERNOS_DE_SOLUCION__DE_CONTROVERSIAS(16L),
    DIRIGIR_A_LA_UNIDAD_DE_FISCALES_INVESTIGADORES_JAR(17L),
    AVISAR_A_LA_UNIDAD_DE_FISCALES_INVESTIGADORES_DEL_NO_CUMPLIMIENTO_DEL_ACUERDO(18L),
    CAPTURAR_ENTREVISTA_INICIAL(19L),
    CAPTURAR_ENTREVISTA_COMPLEMENTARIA(20L),
    RECIBIR_CANALIZACION_EN_LA_UNIDAD_DE_SOLUCION_DE_CONTROVERSIAS(21L),
    ATENDER_CANALIZACION_EN_JUSTICIA_ALTERNATIVA_RESTAURATIVA(22L),
    GENERAR_CONSTANCIA_DE_FALTA_DE_INTERES(23L),
    GENERAR_CITATORIO_PARA_VICTIMA(24L),
    GENERAR_CITATORIO_PARA_PROBABLE_RESPONSABLE(25L),
    ACEPTACION_DEL_SERVICIO_POR_PARTE_DE_LA_VICTIMA(26L),
    ACEPTACION_DEL_SERVICIO_POR_PARTE_DEL_INVITADO(27L),
    LLEVAR_A_CABO_LA_AUDIENCIA_DE_CONCILIACION_MEDIACION(28L),
    GENERAR_CONVENIO_DE_CONCILIACION_MEDIACION(29L),
    AVISAR_DE_CONVENIO_AL_FISCAL_DE_LA_UNIDAD_DE_FISCALES_INVESTIGADORES(30L),
    GENERAR_CONSTANCIA_DE_SEGUIMIENTO_A_CONVENIO(31L),
    ELABORAR_CARTA_DE_CUMPLIMIENTO_DE_ACUERDO(32L),
    ELABORAR_CARTA_DE_FELICITACION(33L),
    AVISAR_A_LA_UNIDAD_DE_FISCALES_INVESTIGADORES_DEL_CUMPLIMIENTO_DEL_ACUERDO(34L),
    GENERAR_DENUNCIA_UI(35L),
    GENERAR_QUERELLA_UI(36L),
    CAPTURAR_DECLARACION_UI(37L),
    RECIBIR_CANALIZACION_EN_LA_UNIDAD_DE_FISCALES_INVESTIGADORES(38L),
    ATENDER_CANALIZACION_EN_LA_UNIDAD_DE_FISCALES_INVESTIGADORES(39L),
    DETERMINAR_NO_INICIO_DE_INVESTIGACION(40L),
    DIRIGIR_A_LA_UNIDAD_DE_SOLUCION_DE_CONTROVERSIAS_UI(41L),
    DIRIGIR_A_INSTANCIA_EXTERNA_UI(42L),
    REGRESAR_A_UNIDAD_DE_SOLUCION_DE_CONTROVERSIAS(43L),
    GENERAR_AVISO_DE_LA_DETENCION_A_LA_DEFENSORIA(44L),
    DICTAR_ACUERDO_DE_RETENCION(45L),
    ELABORAR_OFICIO_INVESTIGACION_POLICIAL(46L),
    ELABORAR_OFICIO_INVESTIGACION_POLICIACA(47L),
    ELABORAR_OFICIO_DE_SOLICITUD_DE_DILIGENCIAS_MINISTERIALES(48L),
    SOLICITAR_DILIGENCIAS_MINISTERIALES(49L),
    ELABORAR_OFICIO_DE_SOLICITUD_DE_DICTAMENES_PERICIALES(50L),
    SOLICITAR_DICTAMENES_PERICIALES(51L),
    ELABORAR_OFICIO_DE_SOLICITUD_DE_ORDEN_DE_APREHENSION(52L),
    SOLICITAR_ORDEN_DE_APREHENSION(53L),
    ELABORAR_OFICIO_DE_SOLICITUD_DE_ORDEN_DE_CATEO(54L),
    SOLICITAR_ORDEN_DE_CATEO(55L),
    ELABORAR_OFICIO_PARA_INTERVENCION_DE_COMUNICACIONES(56L),
    ELABORAR_OFICIO_ORDENANDO_FIJACION_Y_PRESERVACION_DEL_LUGAR_DE_LOS_HECHOS_Y_DEL_HALLAZGO(57L),
    ASENTAR_REGISTRO_DE_CADENA_DE_CUSTODIA_RCC(58L),
    INGRESAR_EVIDENCIA_A_CADENA_DE_CUSTODIA(59L),
    REGISTRAR_ESLABONES_DE_CADENA_DE_CUSTODIA(60L),
    ORDENAR_REPARACION_DEL_DANO(61L),
    GENERAR_DICTAMEN_MOTIVADO_DE_CRITERIO_DE_OPORTUNIDAD(62L),
    GENERAR_RAZONES_PARA_CRITERIO_DE_OPORTUNIDAD(63L),
    INFORMAR_A_PROCURADOR_GENERAL_LA_APLICACION_DE_CRITERIO(64L),
    ARCHIVO_TEMPORAL(65L),
    TURNA_A_SU_SUPERIOR_JERARQUICO_DECISION_DE_REAPERTURA_DEL_ARCHIVO(66L),
    PROMOVER_RECURSOS(67L),
    ARCHIVO_DEFINITIVO(68L),
    GENERAR_OFICIO_A_POLICIA_PARA_LLEVAR_A_CABO_LA_DESTRUCCION_DE_LOS_OBJETOS(69L),
    GENERAR_OFICIO_A_PERITOS_PARA_LLEVAR_A_CABO_LA_DESTRUCCION_DE_LOS_OBJETOS(70L),
    GENERAR_ACTA_DE_DESTRUCCION(71L),
    GENERAR_OFICIO_PARA_NOTIFICAR_AL_PROPIETARIO_DE_LA_DEVOLUCION_DEL_OBJETO(72L),
    GENERAR_OFICIO_PARA_EL_ASEGURAMIENTO_Y_RESGUARDO_DEL_LUGAR(73L),
    GENERAR_OFICIO_PARA_REGISTROS_PUBLICOS(74L),
    COMPARTIR_CARPETA_DE_INVESTIGACION(75L),
    ELABORAR_OFICIO_DE_SOLICITUD_DE_AUDIENCIA_DE_CONTROL_JUDICIAL(76L),
    GENERAR_SOLICITUD_DE_AUDIENCIA_DE_CONTROL_JUDICIAL(77L),
    ELABORAR_OFICIO_DE_SOLICITUD_DE_AUDIENCIA(78L),
    SOLICITAR_AUDIENCIA(79L),
    ELABORAR_OFICIO_DE_SOLICITUD_DE_TRANSCRIPCION_DE_AUDIENCIA(80L),
    SOLICITAR_TRANSCRIPCION_DE_AUDIENCIA(81L),
    SOLICITAR_COPIA_DE_AUDIO_Y_VIDEO_DE_AUDIENCIA(82L),
    ELABORAR_OFICIO_DE_SOLICITUD_DE_COPIA_DE_AUDIO_Y_VIDEO_DE_AUDIENCIA(83L),
    SOLICITAR_SERVICIO_PERICIAL(84L);
    private final static Map<Long, Actuaciones> hash = new HashMap<Long, Actuaciones>();

    static {
        Actuaciones[] acts = Actuaciones.values();
        int pos = 0;
        while (pos < acts.length) {
            hash.put(acts[pos].getValorId(), acts[pos]);
            pos++;
        }
    }

    public static Actuaciones getByValor(Long valorIdPredefinido) {
        return hash.get(valorIdPredefinido);
    }
    private Long valorId;

    private Actuaciones(Long valorIdPredefinido) {
        this.valorId = valorIdPredefinido;
    }

    /**
     * Método de acceso al campo valorId.
     * 
     * @return El valor del campo valorId asociado en le BD.
     */
    public Long getValorId() {
        return valorId;
    }
}
