package mx.gob.segob.nsjp.comun.enums.documento;

import java.util.HashMap;
import java.util.Map;

public enum TipoDocumento {
	SOLICITUD_DEFENSOR_EXTERNO(3001L),  
	TEORIA_DEL_CASO(2382L),
	PLIEGO_DE_CONSIGNACION(1629L),
	CARTA_DE_CUMPLIMIENTO_DE_ACUERDO(2311L),
	
	SOLICITUD (82L),
	ACTA (83L),
	ACUERDO (84L),
	CONSTANCIA (85L),
	ESCRITO (86L),
	INFORME (87L),
	NOTIFICACION (88L),
	OFICIO (89L),
	ACUSE  (1780L),
	DOCUMENTO (2283L),
	NOTIFICACION_O_CITATORIO (2284L),
	SOLICITUD_DE_ASESORIA_LEGAL (2293L),
	OFICIO_DE_CANALIZACION_A_LA_UNIDAD_DE_SOLUCION_DE_CONTROVERSIAS (2294L),
	OFICIO_DE_SOLICITUD_DE_ATENCION_PSICOLOGICA (2295L),
	FICHA_DE_CANALIZACION_A_LA_UNIDAD_DE_FISCALES_INVESTIGADORES (2296L),
	OFICIO_DE_SOLICITUD_DE_ATENCION_MEDICA (2297L),
	OFICIO_DE_REMISION_POR_INCOMPETENCIA (2298L),
	OFICIO_DE_SOLICITUD_DE_ASESORIA_JURIDICA (2299L),
	ARCHIVO_ADJUNTADO (2300L),
	SOLICITUD_DE_ATENCION_MEDICA (2301L),
	OFICIO_DE_NO_CUMPLIMIENTO_DE_ACUERDO_PARA_LA_UNIDAD_DE_FISCALES_INVESTIGADORES (2302L),
	SOLICITUD_DE_ATENCION_PSICOLOGICA(2303L),
	ENTREVISTA_INICIAL(2304L),
	AVISO_DE_QUE_LA_DENUNCIA_O_QUERELLA_SE_DIRIGIO_A_LA_UNIDAD_DE_MEDIOS_ALTERNOS_DE_SOLUCION_DE_CONTROVERSIAS(2305L),
	SOLICITUD_DE_SEGURIDAD_POLICIAL(2306L),
	OFICIO_DE_SOLICITUD_DE_SEGURIDAD_POLICIAL(2307L),
	CONVENIO_DE_CONFIDENCIALIDAD(2308L),
	OFICIO_DE_CUMPLIMIENTO_DE_ACUERDO_PARA_LA_UNIDAD_DE_FISCALES_INVESTIGADORES(2309L),
	ACTA_DE_NO_INICIO_DE_INVESTIGACION(2310L),
	CARTA_DE_ACEPTACION_DEL_SERVICIO_POR_PARTE_DEL_INVITADO(2312L),
	INVITACION_A_VICTIMA(2313L),
	CARTA_DE_ACEPTACION_DEL_SERVICIO_POR_PARTE_DE_LA_VICTIMA(2314L),
	CARTA_DE_FELICITACION(2315L),
	INVITACION_A_PROBABLE_RESPONSABLE(2316L),
	CONSTANCIA_DE_FALTA_DE_INTERES(2317L),
	AVISO_DE_EXISTENCIA_DE_CONVENIO(2318L),
	CONVENIO_DE_CONCILIACION_MEDIACION(2319L),
	CONSTANCIA_DE_SEGUIMIENTO_A_CONVENIO(2320L),
	OFICIO_INVESTIGACION_POLICIACA(2321L),
	OFICIO_DE_SOLICITUD_DE_DICTAMENES_PERICIALES(2322L),
	OFICIO_ORDENANDO_FIJACION_Y_PRESERVACION_DEL_LUGAR_DE_LOS_HECHOS_O_DEL_HALLAZGO(2323L),
	OFICIO_DE_SOLICITUD_DE_ORDEN_DE_APREHENSION(2324L),
	SOLICITUD_DE_DICTAMENES_PERICIALES(2325L),
	OFICIO_DE_INVESTIGACION_POLICIAL(2326L),
	OFICIO_DE_SOLICITUD_DE_ORDEN_DE_CATEO(2327L),
	OFICIO_DE_INTERVENCION_DE_COMUNICACIONES(2328L),
	ACUERDO_DE_RETENCION(2329L),
	AVISO_DE_DETENCION_A_LA_DEFENSORIA(2330L),
	OFICIO_DE_SOLICITUD_DE_DILIGENCIAS_MINISTERIALES(2331L),
	ORDEN_DE_REPARACION_DEL_DANIO(2332L),
	OFICIO_DE_SOLICITUD_DE_AUDIENCIA(2333L),
	OFICIO_DE_NOTIFICACION_A_REGISTROS_PUBLICOS(2334L),
	SOLICITUD_DE_AUDIENCIA(2335L),
	OFICIO_PARA_EL_ASEGURAMIENTO_Y_RESGUARDO_DEL_LUGAR_DE_LOS_HECHOS_O_DEL_HALLAZGO(2336L),
	OFICIO_A_LA_POLICIA_PARA_LLEVAR_A_CABO_LA_DESTRUCCION_DE_LOS_OBJETOS(2337L),
	RAZONES_PARA_CRITERIO_DE_OPORTUNIDAD(2338L),
	ARCHIVO_DEFINITIVO_DEL_CASO(2339L),
	ACTA_DE_DESTRUCCION_DE_OBJETOS(2340L),
	INFORME_DE_CRITERIO_DE_OPORTUNIDAD(2341L),
	OFICIO_DE_SOLICITUD_DE_AUDIENCIA_DE_CONTROL_JUDICIAL(2342L),
	OFICIO_PARA_NOTIFICAR_AL_PROPIETARIO_SOBRE_LA_DEVOLUCION_DEL_OBJETO(2343L),
	ESCRITO_DE_EXPRESION_DE_AGRAVIOS(2344L),
	SOLICITUD_DE_AUDIENCIA_DE_CONTROL_JUDICIAL(2345L),
	OFICIO_A_PERITOS_SOLICITANDO_DICTAMEN_SOBRE_LA_DESTRUCCION_TOTAL_DE_LOS_OBJETOS(2346L),
	DICTAMEN_MOTIVADO_DE_CRITERIO_DE_OPORTUNIDAD(2347L),
	NOTIFICAR_A_LA_VICTIMA_ACERCA_DE_INSUFICIENCIA_DE_ELEMENTOS(2348L),
	VISOR_DE_ELEMENTOS_Y_PDFS_RELACIONADOS(2349L),
	OFICIO_A_SU_SUPERIOR_JERARQUICO_INFORMANDO_DECISION_DE_REAPERTURA_DEL_ARCHIVO(2350L),
	OFICIO_DE_SOLICITUD_DE_TRANSCRIPCION_DE_AUDIENCIA(2351L),
	OFICIO_DE_SOLICITUD_DE_COPIA_DE_AUDIO_Y_VIDEO_DE_AUDIENCIA(2352L),
	SOLICITUD_DE_COPIA_DE_AUDIO_Y_VIDEO_DE_AUDIENCIA(2353L),
	SOLICITUD_TRANSCRIPCION_DE_AUDIENCIA(2354L),
	ENTREVISTA_COMPLEMENTARIA(2356L),
	OFICIO_DE_SOLICITUD_A_UNIDAD_DE_ATENCION_A_VICTIMAS_DEL_DELITO(2374L),
	MINISTERIAL(2375L),
	CANALIZACION(2376L),
	SOLICITUD_A_UNIDAD_DE_ATENCION_A_VICTIMAS_DEL_DELITO(2377L),
	AVISO_DE_CANALIZACION(2378L),
	PERICIALES(2379L),
	AUDIENCIAS(2380L),
	POLICIA_MINISTERIAL(2381L),
	SOLICITUD_DE_SERVICIO_PERICIAL(2409L),
	MEDIDA(2411L),AMPARO(299L),
	MANDAMIENTO_JUDICIAL(6372L),
	MEDIDA_CAUTELAR(6382L),
	CAMBIO_DE_ESTADO_DE_MEDIDA_CAUTELAR(6383L),
	CAMBIO_DE_ESTADO_DE_MANDAMIENTO_JUDICIAL(6384L),
	AUTO_INICIO_PROCEDIMIENTO_EJECUCION(7084L),
	SENTENCIA_EJECUTORIADA(7085L),
	ACUERDO_AUTORIZACION_REMISION_PARCIAL_PENA(7156L),
	ACUERDO_AUTORIZACION_LIBERTAD_CONDICIONAL(7451L),
	ACUERDO_AUTORIZACION_EXTINCION_MULTA(7487L),
	ACUERDO_AUTORIZACION_EXTINCION_REPARACION_DANIO(7493L),
	REPORTE_CUMPLIMIENTO_MANDAMIENTO_JUDICIAL(7638L),
	SEGUIMIENTO_A_OFICIO_DE_CUMPLIMIENTO_DE_MANDAMIENTO_JUDICIAL(9841L),
	ARCHIVO_AUDIO(9933L),ARCHIVO_IMAGEN(9934L);
	
	
    private final static Map<Long, TipoDocumento> hash = new HashMap<Long, TipoDocumento>();

    static {
    	TipoDocumento[] acts = TipoDocumento.values();
        int pos = 0;
        while (pos < acts.length) {
            hash.put(acts[pos].getValorId(), acts[pos]);
            pos++;
        }
    }

    private Long valorId;

    private TipoDocumento(Long valorIdPredefinido) {
        this.valorId = valorIdPredefinido;
    }

    /**
     * Método de acceso al campo valorId.
     * 
     * @return El valor del campo valorId asociado en le BD.
     */
    public Long getValorId() {
        return valorId;
    }
 
    /**
     * 
     * @param valorIdPredefinido
     * @return
     */
    public static TipoDocumento getByValor(Long valorIdPredefinido) {
        return hash.get(valorIdPredefinido);
    }
}
