package mx.gob.segob.nsjp.ws.cliente.solicituddefensor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:52.314-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "RegistrarSolicitudDefensorAreaExternaExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface RegistrarSolicitudDefensorAreaExternaExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/RegistrarSolicitudDefensorAreaExternaExporter/registrarSolicitudDefensorRequest", output = "http://ws.service.nsjp.segob.gob.mx/RegistrarSolicitudDefensorAreaExternaExporter/registrarSolicitudDefensorResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/RegistrarSolicitudDefensorAreaExternaExporter/registrarSolicitudDefensor/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "registrarSolicitudDefensor", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.solicituddefensor.RegistrarSolicitudDefensor")
    @WebMethod
    @ResponseWrapper(localName = "registrarSolicitudDefensorResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.solicituddefensor.RegistrarSolicitudDefensorResponse")
    public mx.gob.segob.nsjp.ws.cliente.solicituddefensor.SolicitudDefensorWSDTO registrarSolicitudDefensor(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.solicituddefensor.SolicitudDefensorWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
