package mx.gob.segob.nsjp.ws.cliente.solicituddefensor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:52.328-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "RegistrarSolicitudDefensorAreaExternaExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/RegistrarSolicitudDefensorAreaExternaExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class RegistrarSolicitudDefensorAreaExternaExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarSolicitudDefensorAreaExternaExporterImplService");
    public final static QName RegistrarSolicitudDefensorAreaExternaExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarSolicitudDefensorAreaExternaExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/RegistrarSolicitudDefensorAreaExternaExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegistrarSolicitudDefensorAreaExternaExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/RegistrarSolicitudDefensorAreaExternaExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegistrarSolicitudDefensorAreaExternaExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistrarSolicitudDefensorAreaExternaExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrarSolicitudDefensorAreaExternaExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RegistrarSolicitudDefensorAreaExternaExporter
     */
    @WebEndpoint(name = "RegistrarSolicitudDefensorAreaExternaExporterImplPort")
    public RegistrarSolicitudDefensorAreaExternaExporter getRegistrarSolicitudDefensorAreaExternaExporterImplPort() {
        return super.getPort(RegistrarSolicitudDefensorAreaExternaExporterImplPort, RegistrarSolicitudDefensorAreaExternaExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrarSolicitudDefensorAreaExternaExporter
     */
    @WebEndpoint(name = "RegistrarSolicitudDefensorAreaExternaExporterImplPort")
    public RegistrarSolicitudDefensorAreaExternaExporter getRegistrarSolicitudDefensorAreaExternaExporterImplPort(WebServiceFeature... features) {
        return super.getPort(RegistrarSolicitudDefensorAreaExternaExporterImplPort, RegistrarSolicitudDefensorAreaExternaExporter.class, features);
    }

}
