package mx.gob.segob.nsjp.ws.cliente.enviardocumentoincumplimientomedida;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:26.237-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "EnviarDocumentoIncumplimientoMedidaExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/EnviarDocumentoIncumplimientoMedidaExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class EnviarDocumentoIncumplimientoMedidaExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "EnviarDocumentoIncumplimientoMedidaExporterImplService");
    public final static QName EnviarDocumentoIncumplimientoMedidaExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "EnviarDocumentoIncumplimientoMedidaExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/EnviarDocumentoIncumplimientoMedidaExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EnviarDocumentoIncumplimientoMedidaExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/EnviarDocumentoIncumplimientoMedidaExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EnviarDocumentoIncumplimientoMedidaExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EnviarDocumentoIncumplimientoMedidaExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnviarDocumentoIncumplimientoMedidaExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns EnviarDocumentoIncumplimientoMedidaExporter
     */
    @WebEndpoint(name = "EnviarDocumentoIncumplimientoMedidaExporterImplPort")
    public EnviarDocumentoIncumplimientoMedidaExporter getEnviarDocumentoIncumplimientoMedidaExporterImplPort() {
        return super.getPort(EnviarDocumentoIncumplimientoMedidaExporterImplPort, EnviarDocumentoIncumplimientoMedidaExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnviarDocumentoIncumplimientoMedidaExporter
     */
    @WebEndpoint(name = "EnviarDocumentoIncumplimientoMedidaExporterImplPort")
    public EnviarDocumentoIncumplimientoMedidaExporter getEnviarDocumentoIncumplimientoMedidaExporterImplPort(WebServiceFeature... features) {
        return super.getPort(EnviarDocumentoIncumplimientoMedidaExporterImplPort, EnviarDocumentoIncumplimientoMedidaExporter.class, features);
    }

}
