package mx.gob.segob.nsjp.ws.cliente.seguimiento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:08.239-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "ActualizarSeguimientoMandamientoMedidaExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/ActualizarSeguimientoMandamientoMedidaExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class ActualizarSeguimientoMandamientoMedidaExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ActualizarSeguimientoMandamientoMedidaExporterImplService");
    public final static QName ActualizarSeguimientoMandamientoMedidaExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ActualizarSeguimientoMandamientoMedidaExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/ActualizarSeguimientoMandamientoMedidaExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ActualizarSeguimientoMandamientoMedidaExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/ActualizarSeguimientoMandamientoMedidaExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ActualizarSeguimientoMandamientoMedidaExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ActualizarSeguimientoMandamientoMedidaExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActualizarSeguimientoMandamientoMedidaExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ActualizarSeguimientoMandamientoMedidaExporter
     */
    @WebEndpoint(name = "ActualizarSeguimientoMandamientoMedidaExporterImplPort")
    public ActualizarSeguimientoMandamientoMedidaExporter getActualizarSeguimientoMandamientoMedidaExporterImplPort() {
        return super.getPort(ActualizarSeguimientoMandamientoMedidaExporterImplPort, ActualizarSeguimientoMandamientoMedidaExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ActualizarSeguimientoMandamientoMedidaExporter
     */
    @WebEndpoint(name = "ActualizarSeguimientoMandamientoMedidaExporterImplPort")
    public ActualizarSeguimientoMandamientoMedidaExporter getActualizarSeguimientoMandamientoMedidaExporterImplPort(WebServiceFeature... features) {
        return super.getPort(ActualizarSeguimientoMandamientoMedidaExporterImplPort, ActualizarSeguimientoMandamientoMedidaExporter.class, features);
    }

}
