package mx.gob.segob.nsjp.ws.cliente.seguimiento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:08.226-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "ActualizarSeguimientoMandamientoMedidaExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface ActualizarSeguimientoMandamientoMedidaExporter {

    @Action(input = "http://ws.service.nsjp.segob.gob.mx/ActualizarSeguimientoMandamientoMedidaExporter/actualizarSeguimientoRequest", output = "http://ws.service.nsjp.segob.gob.mx/ActualizarSeguimientoMandamientoMedidaExporter/actualizarSeguimientoResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/ActualizarSeguimientoMandamientoMedidaExporter/actualizarSeguimiento/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "actualizarSeguimiento", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.seguimiento.ActualizarSeguimiento")
    @WebMethod
    @ResponseWrapper(localName = "actualizarSeguimientoResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.seguimiento.ActualizarSeguimientoResponse")
    public void actualizarSeguimiento(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.seguimiento.SeguimientoMandamientoMedidaWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
