package mx.gob.segob.nsjp.ws.cliente.solicitudtranscripcion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-13T13:22:35.219-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "RegistrarSolicitudTranscripcionAreaExternaExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/RegistrarSolicitudTranscripcionAreaExternaExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class RegistrarSolicitudTranscripcionAreaExternaExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarSolicitudTranscripcionAreaExternaExporterImplService");
    public final static QName RegistrarSolicitudTranscripcionAreaExternaExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarSolicitudTranscripcionAreaExternaExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/RegistrarSolicitudTranscripcionAreaExternaExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegistrarSolicitudTranscripcionAreaExternaExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/RegistrarSolicitudTranscripcionAreaExternaExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegistrarSolicitudTranscripcionAreaExternaExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistrarSolicitudTranscripcionAreaExternaExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrarSolicitudTranscripcionAreaExternaExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RegistrarSolicitudTranscripcionAreaExternaExporter
     */
    @WebEndpoint(name = "RegistrarSolicitudTranscripcionAreaExternaExporterImplPort")
    public RegistrarSolicitudTranscripcionAreaExternaExporter getRegistrarSolicitudTranscripcionAreaExternaExporterImplPort() {
        return super.getPort(RegistrarSolicitudTranscripcionAreaExternaExporterImplPort, RegistrarSolicitudTranscripcionAreaExternaExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrarSolicitudTranscripcionAreaExternaExporter
     */
    @WebEndpoint(name = "RegistrarSolicitudTranscripcionAreaExternaExporterImplPort")
    public RegistrarSolicitudTranscripcionAreaExternaExporter getRegistrarSolicitudTranscripcionAreaExternaExporterImplPort(WebServiceFeature... features) {
        return super.getPort(RegistrarSolicitudTranscripcionAreaExternaExporterImplPort, RegistrarSolicitudTranscripcionAreaExternaExporter.class, features);
    }

}
