package mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:10.132-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "AdministrarPermisosAudienciaExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface AdministrarPermisosAudienciaExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/consultarPermisoAudienciaUsuarioExternoRequest", output = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/consultarPermisoAudienciaUsuarioExternoResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/consultarPermisoAudienciaUsuarioExterno/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "consultarPermisoAudienciaUsuarioExterno", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.ConsultarPermisoAudienciaUsuarioExterno")
    @WebMethod
    @ResponseWrapper(localName = "consultarPermisoAudienciaUsuarioExternoResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.ConsultarPermisoAudienciaUsuarioExternoResponse")
    public mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.AudienciaJAVSTransporteWSDTO consultarPermisoAudienciaUsuarioExterno(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.FuncionarioExternoWSDTO arg0
    ) throws NSJPNegocioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/consultarParametrosConsultaAudienciaJavsRequest", output = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/consultarParametrosConsultaAudienciaJavsResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/consultarParametrosConsultaAudienciaJavs/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "consultarParametrosConsultaAudienciaJavs", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.ConsultarParametrosConsultaAudienciaJavs")
    @WebMethod
    @ResponseWrapper(localName = "consultarParametrosConsultaAudienciaJavsResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.ConsultarParametrosConsultaAudienciaJavsResponse")
    public mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.AudienciaJAVSTransporteWSDTO consultarParametrosConsultaAudienciaJavs(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    ) throws NSJPNegocioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/consultarDirectoriosConsultaJAVSRequest", output = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/consultarDirectoriosConsultaJAVSResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/consultarDirectoriosConsultaJAVS/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "consultarDirectoriosConsultaJAVS", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.ConsultarDirectoriosConsultaJAVS")
    @WebMethod
    @ResponseWrapper(localName = "consultarDirectoriosConsultaJAVSResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.ConsultarDirectoriosConsultaJAVSResponse")
    public byte[] consultarDirectoriosConsultaJAVS(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    ) throws NSJPNegocioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/consultarRegistroMaestroJVLRequest", output = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/consultarRegistroMaestroJVLResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/consultarRegistroMaestroJVL/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "consultarRegistroMaestroJVL", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.ConsultarRegistroMaestroJVL")
    @WebMethod
    @ResponseWrapper(localName = "consultarRegistroMaestroJVLResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.ConsultarRegistroMaestroJVLResponse")
    public byte[] consultarRegistroMaestroJVL(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    ) throws NSJPNegocioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/datosConexionRequest", output = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/datosConexionResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/datosConexion/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "datosConexion", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.DatosConexion")
    @WebMethod
    @ResponseWrapper(localName = "datosConexionResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.DatosConexionResponse")
    public java.lang.String datosConexion(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    ) throws NSJPNegocioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/generarPermisoUsuarioExternoRequest", output = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/generarPermisoUsuarioExternoResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/AdministrarPermisosAudienciaExporter/generarPermisoUsuarioExterno/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "generarPermisoUsuarioExterno", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.GenerarPermisoUsuarioExterno")
    @WebMethod
    @ResponseWrapper(localName = "generarPermisoUsuarioExternoResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.GenerarPermisoUsuarioExternoResponse")
    public java.lang.Long generarPermisoUsuarioExterno(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia.FuncionarioExternoWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
