package mx.gob.segob.nsjp.ws.cliente.administrarPermisosAudiencia;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:10.158-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "AdministrarPermisosAudienciaExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/AdministrarPermisosAudienciaExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class AdministrarPermisosAudienciaExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "AdministrarPermisosAudienciaExporterImplService");
    public final static QName AdministrarPermisosAudienciaExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "AdministrarPermisosAudienciaExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/AdministrarPermisosAudienciaExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AdministrarPermisosAudienciaExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/AdministrarPermisosAudienciaExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AdministrarPermisosAudienciaExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdministrarPermisosAudienciaExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdministrarPermisosAudienciaExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AdministrarPermisosAudienciaExporter
     */
    @WebEndpoint(name = "AdministrarPermisosAudienciaExporterImplPort")
    public AdministrarPermisosAudienciaExporter getAdministrarPermisosAudienciaExporterImplPort() {
        return super.getPort(AdministrarPermisosAudienciaExporterImplPort, AdministrarPermisosAudienciaExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdministrarPermisosAudienciaExporter
     */
    @WebEndpoint(name = "AdministrarPermisosAudienciaExporterImplPort")
    public AdministrarPermisosAudienciaExporter getAdministrarPermisosAudienciaExporterImplPort(WebServiceFeature... features) {
        return super.getPort(AdministrarPermisosAudienciaExporterImplPort, AdministrarPermisosAudienciaExporter.class, features);
    }

}
