package mx.gob.segob.nsjp.ws.cliente.consultaraudiencia;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2014-04-30T12:39:02.476-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "ConsultarAudienciasByFechasYEstatusExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/ConsultarAudienciasByFechasYEstatusExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class ConsultarAudienciasByFechasYEstatusExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ConsultarAudienciasByFechasYEstatusExporterImplService");
    public final static QName ConsultarAudienciasByFechasYEstatusExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ConsultarAudienciasByFechasYEstatusExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/ConsultarAudienciasByFechasYEstatusExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultarAudienciasByFechasYEstatusExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/ConsultarAudienciasByFechasYEstatusExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultarAudienciasByFechasYEstatusExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultarAudienciasByFechasYEstatusExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarAudienciasByFechasYEstatusExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ConsultarAudienciasByFechasYEstatusExporter
     */
    @WebEndpoint(name = "ConsultarAudienciasByFechasYEstatusExporterImplPort")
    public ConsultarAudienciasByFechasYEstatusExporter getConsultarAudienciasByFechasYEstatusExporterImplPort() {
        return super.getPort(ConsultarAudienciasByFechasYEstatusExporterImplPort, ConsultarAudienciasByFechasYEstatusExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarAudienciasByFechasYEstatusExporter
     */
    @WebEndpoint(name = "ConsultarAudienciasByFechasYEstatusExporterImplPort")
    public ConsultarAudienciasByFechasYEstatusExporter getConsultarAudienciasByFechasYEstatusExporterImplPort(WebServiceFeature... features) {
        return super.getPort(ConsultarAudienciasByFechasYEstatusExporterImplPort, ConsultarAudienciasByFechasYEstatusExporter.class, features);
    }

}
