
package mx.gob.segob.nsjp.ws.cliente.consultaraudiencia;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2014-04-30T12:39:02.289-05:00
 * Generated source version: 2.4.2
 * 
 */
public final class ConsultarAudienciasByFechasYEstatusExporter_ConsultarAudienciasByFechasYEstatusExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ConsultarAudienciasByFechasYEstatusExporterImplService");

    private ConsultarAudienciasByFechasYEstatusExporter_ConsultarAudienciasByFechasYEstatusExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConsultarAudienciasByFechasYEstatusExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ConsultarAudienciasByFechasYEstatusExporterImplService ss = new ConsultarAudienciasByFechasYEstatusExporterImplService(wsdlURL, SERVICE_NAME);
        ConsultarAudienciasByFechasYEstatusExporter port = ss.getConsultarAudienciasByFechasYEstatusExporterImplPort();  
        
        {
        System.out.println("Invoking consultarAudienciasByFechasYEstatus...");
        mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO _consultarAudienciasByFechasYEstatus_arg0 = null;
        try {
            java.util.List<mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO> _consultarAudienciasByFechasYEstatus__return = port.consultarAudienciasByFechasYEstatus(_consultarAudienciasByFechasYEstatus_arg0);
            System.out.println("consultarAudienciasByFechasYEstatus.result=" + _consultarAudienciasByFechasYEstatus__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultarAudienciaById...");
        mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO _consultarAudienciaById_arg0 = null;
        try {
            mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO _consultarAudienciaById__return = port.consultarAudienciaById(_consultarAudienciaById_arg0);
            System.out.println("consultarAudienciaById.result=" + _consultarAudienciaById__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultarAudienciasPorFechasYSolicitudTranscripcion...");
        mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO _consultarAudienciasPorFechasYSolicitudTranscripcion_arg0 = null;
        try {
            java.util.List<mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO> _consultarAudienciasPorFechasYSolicitudTranscripcion__return = port.consultarAudienciasPorFechasYSolicitudTranscripcion(_consultarAudienciasPorFechasYSolicitudTranscripcion_arg0);
            System.out.println("consultarAudienciasPorFechasYSolicitudTranscripcion.result=" + _consultarAudienciasPorFechasYSolicitudTranscripcion__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultarIndicadorDeAudienciasPorFechas...");
        java.lang.String _consultarIndicadorDeAudienciasPorFechas_arg0 = "";
        java.lang.String _consultarIndicadorDeAudienciasPorFechas_arg1 = "";
        try {
            java.util.List<java.lang.String> _consultarIndicadorDeAudienciasPorFechas__return = port.consultarIndicadorDeAudienciasPorFechas(_consultarIndicadorDeAudienciasPorFechas_arg0, _consultarIndicadorDeAudienciasPorFechas_arg1);
            System.out.println("consultarIndicadorDeAudienciasPorFechas.result=" + _consultarIndicadorDeAudienciasPorFechas__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
