package mx.gob.segob.nsjp.ws.cliente.avisodetencion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:42.193-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "RegistrarAvisoDetencionDeAreaExternaExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface RegistrarAvisoDetencionDeAreaExternaExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/RegistrarAvisoDetencionDeAreaExternaExporter/registrarAvisoDetencionRequest", output = "http://ws.service.nsjp.segob.gob.mx/RegistrarAvisoDetencionDeAreaExternaExporter/registrarAvisoDetencionResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/RegistrarAvisoDetencionDeAreaExternaExporter/registrarAvisoDetencion/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "registrarAvisoDetencion", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.avisodetencion.RegistrarAvisoDetencion")
    @WebMethod
    @ResponseWrapper(localName = "registrarAvisoDetencionResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.avisodetencion.RegistrarAvisoDetencionResponse")
    public mx.gob.segob.nsjp.ws.cliente.avisodetencion.AvisoDetencionWSDTO registrarAvisoDetencion(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.avisodetencion.AvisoDetencionWSDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.Long arg3
    ) throws NSJPNegocioException_Exception;
}
