package mx.gob.segob.nsjp.ws.cliente.avisodetencion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:42.212-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "RegistrarAvisoDetencionDeAreaExternaExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/RegistrarAvisoDetencionDeAreaExternaExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class RegistrarAvisoDetencionDeAreaExternaExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarAvisoDetencionDeAreaExternaExporterImplService");
    public final static QName RegistrarAvisoDetencionDeAreaExternaExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarAvisoDetencionDeAreaExternaExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/RegistrarAvisoDetencionDeAreaExternaExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegistrarAvisoDetencionDeAreaExternaExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/RegistrarAvisoDetencionDeAreaExternaExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegistrarAvisoDetencionDeAreaExternaExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistrarAvisoDetencionDeAreaExternaExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrarAvisoDetencionDeAreaExternaExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RegistrarAvisoDetencionDeAreaExternaExporter
     */
    @WebEndpoint(name = "RegistrarAvisoDetencionDeAreaExternaExporterImplPort")
    public RegistrarAvisoDetencionDeAreaExternaExporter getRegistrarAvisoDetencionDeAreaExternaExporterImplPort() {
        return super.getPort(RegistrarAvisoDetencionDeAreaExternaExporterImplPort, RegistrarAvisoDetencionDeAreaExternaExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrarAvisoDetencionDeAreaExternaExporter
     */
    @WebEndpoint(name = "RegistrarAvisoDetencionDeAreaExternaExporterImplPort")
    public RegistrarAvisoDetencionDeAreaExternaExporter getRegistrarAvisoDetencionDeAreaExternaExporterImplPort(WebServiceFeature... features) {
        return super.getPort(RegistrarAvisoDetencionDeAreaExternaExporterImplPort, RegistrarAvisoDetencionDeAreaExternaExporter.class, features);
    }

}
