package mx.gob.segob.nsjp.ws.cliente.consultarfuncionariosxtribunal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:18.245-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "ConsultarFuncionariosXTribunalExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/ConsultarFuncionariosXTribunalExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class ConsultarFuncionariosXTribunalExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ConsultarFuncionariosXTribunalExporterImplService");
    public final static QName ConsultarFuncionariosXTribunalExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ConsultarFuncionariosXTribunalExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/ConsultarFuncionariosXTribunalExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultarFuncionariosXTribunalExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/ConsultarFuncionariosXTribunalExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultarFuncionariosXTribunalExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultarFuncionariosXTribunalExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarFuncionariosXTribunalExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ConsultarFuncionariosXTribunalExporter
     */
    @WebEndpoint(name = "ConsultarFuncionariosXTribunalExporterImplPort")
    public ConsultarFuncionariosXTribunalExporter getConsultarFuncionariosXTribunalExporterImplPort() {
        return super.getPort(ConsultarFuncionariosXTribunalExporterImplPort, ConsultarFuncionariosXTribunalExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarFuncionariosXTribunalExporter
     */
    @WebEndpoint(name = "ConsultarFuncionariosXTribunalExporterImplPort")
    public ConsultarFuncionariosXTribunalExporter getConsultarFuncionariosXTribunalExporterImplPort(WebServiceFeature... features) {
        return super.getPort(ConsultarFuncionariosXTribunalExporterImplPort, ConsultarFuncionariosXTribunalExporter.class, features);
    }

}
