package mx.gob.segob.nsjp.ws.cliente.medidacautelar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:47.942-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "RegistrarMedidaCautelarServiceExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/RegistrarMedidaCautelarServiceExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class RegistrarMedidaCautelarServiceExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarMedidaCautelarServiceExporterImplService");
    public final static QName RegistrarMedidaCautelarServiceExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarMedidaCautelarServiceExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/RegistrarMedidaCautelarServiceExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegistrarMedidaCautelarServiceExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/RegistrarMedidaCautelarServiceExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegistrarMedidaCautelarServiceExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistrarMedidaCautelarServiceExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrarMedidaCautelarServiceExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RegistrarMedidaCautelarServiceExporter
     */
    @WebEndpoint(name = "RegistrarMedidaCautelarServiceExporterImplPort")
    public RegistrarMedidaCautelarServiceExporter getRegistrarMedidaCautelarServiceExporterImplPort() {
        return super.getPort(RegistrarMedidaCautelarServiceExporterImplPort, RegistrarMedidaCautelarServiceExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrarMedidaCautelarServiceExporter
     */
    @WebEndpoint(name = "RegistrarMedidaCautelarServiceExporterImplPort")
    public RegistrarMedidaCautelarServiceExporter getRegistrarMedidaCautelarServiceExporterImplPort(WebServiceFeature... features) {
        return super.getPort(RegistrarMedidaCautelarServiceExporterImplPort, RegistrarMedidaCautelarServiceExporter.class, features);
    }

}
