
package mx.gob.segob.nsjp.ws.cliente.sentencia;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:46:00.059-05:00
 * Generated source version: 2.4.2
 * 
 */
public final class SentenciaExporterImpl_SentenciaExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "SentenciaExporterImplService");

    private SentenciaExporterImpl_SentenciaExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SentenciaExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SentenciaExporterImplService ss = new SentenciaExporterImplService(wsdlURL, SERVICE_NAME);
        SentenciaExporterImpl port = ss.getSentenciaExporterImplPort();  
        
        {
        System.out.println("Invoking crearSentencia...");
        mx.gob.segob.nsjp.ws.cliente.sentencia.SentenciaWSDTO _crearSentencia_arg0 = null;
        try {
            port.crearSentencia(_crearSentencia_arg0);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
