package mx.gob.segob.nsjp.ws.cliente.sentencia;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:46:00.173-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "SentenciaExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/SentenciaExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class SentenciaExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "SentenciaExporterImplService");
    public final static QName SentenciaExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "SentenciaExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/SentenciaExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SentenciaExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/SentenciaExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SentenciaExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SentenciaExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SentenciaExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SentenciaExporterImpl
     */
    @WebEndpoint(name = "SentenciaExporterImplPort")
    public SentenciaExporterImpl getSentenciaExporterImplPort() {
        return super.getPort(SentenciaExporterImplPort, SentenciaExporterImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SentenciaExporterImpl
     */
    @WebEndpoint(name = "SentenciaExporterImplPort")
    public SentenciaExporterImpl getSentenciaExporterImplPort(WebServiceFeature... features) {
        return super.getPort(SentenciaExporterImplPort, SentenciaExporterImpl.class, features);
    }

}
