package mx.gob.segob.nsjp.ws.cliente.recibiractualizacionmandamiento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:46:07.310-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "RecibirActualizacionMandamientoInterInstitucionalExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface RecibirActualizacionMandamientoInterInstitucionalExporter {

    @Action(input = "http://ws.service.nsjp.segob.gob.mx/RecibirActualizacionMandamientoInterInstitucionalExporter/recibirActualizacionMandamientoInterInstitucionalRequest", output = "http://ws.service.nsjp.segob.gob.mx/RecibirActualizacionMandamientoInterInstitucionalExporter/recibirActualizacionMandamientoInterInstitucionalResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/RecibirActualizacionMandamientoInterInstitucionalExporter/recibirActualizacionMandamientoInterInstitucional/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "recibirActualizacionMandamientoInterInstitucional", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.recibiractualizacionmandamiento.RecibirActualizacionMandamientoInterInstitucional")
    @WebMethod
    @ResponseWrapper(localName = "recibirActualizacionMandamientoInterInstitucionalResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.recibiractualizacionmandamiento.RecibirActualizacionMandamientoInterInstitucionalResponse")
    public void recibirActualizacionMandamientoInterInstitucional(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.recibiractualizacionmandamiento.MandamientoWSDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.recibiractualizacionmandamiento.DocumentoWSDTO arg1
    ) throws NSJPNegocioException_Exception;
}
