package mx.gob.segob.nsjp.ws.cliente.recibiractualizacionmandamiento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:46:07.322-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "RecibirActualizacionMandamientoInterInstitucionalExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/RecibirActualizacionMandamientoInterInstitucionalExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class RecibirActualizacionMandamientoInterInstitucionalExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RecibirActualizacionMandamientoInterInstitucionalExporterImplService");
    public final static QName RecibirActualizacionMandamientoInterInstitucionalExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RecibirActualizacionMandamientoInterInstitucionalExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/RecibirActualizacionMandamientoInterInstitucionalExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RecibirActualizacionMandamientoInterInstitucionalExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/RecibirActualizacionMandamientoInterInstitucionalExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RecibirActualizacionMandamientoInterInstitucionalExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RecibirActualizacionMandamientoInterInstitucionalExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecibirActualizacionMandamientoInterInstitucionalExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RecibirActualizacionMandamientoInterInstitucionalExporter
     */
    @WebEndpoint(name = "RecibirActualizacionMandamientoInterInstitucionalExporterImplPort")
    public RecibirActualizacionMandamientoInterInstitucionalExporter getRecibirActualizacionMandamientoInterInstitucionalExporterImplPort() {
        return super.getPort(RecibirActualizacionMandamientoInterInstitucionalExporterImplPort, RecibirActualizacionMandamientoInterInstitucionalExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecibirActualizacionMandamientoInterInstitucionalExporter
     */
    @WebEndpoint(name = "RecibirActualizacionMandamientoInterInstitucionalExporterImplPort")
    public RecibirActualizacionMandamientoInterInstitucionalExporter getRecibirActualizacionMandamientoInterInstitucionalExporterImplPort(WebServiceFeature... features) {
        return super.getPort(RecibirActualizacionMandamientoInterInstitucionalExporterImplPort, RecibirActualizacionMandamientoInterInstitucionalExporter.class, features);
    }

}
