
package mx.gob.segob.nsjp.ws.cliente.recibiractualizacionmandamiento;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:46:07.206-05:00
 * Generated source version: 2.4.2
 * 
 */
public final class RecibirActualizacionMandamientoInterInstitucionalExporter_RecibirActualizacionMandamientoInterInstitucionalExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RecibirActualizacionMandamientoInterInstitucionalExporterImplService");

    private RecibirActualizacionMandamientoInterInstitucionalExporter_RecibirActualizacionMandamientoInterInstitucionalExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RecibirActualizacionMandamientoInterInstitucionalExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RecibirActualizacionMandamientoInterInstitucionalExporterImplService ss = new RecibirActualizacionMandamientoInterInstitucionalExporterImplService(wsdlURL, SERVICE_NAME);
        RecibirActualizacionMandamientoInterInstitucionalExporter port = ss.getRecibirActualizacionMandamientoInterInstitucionalExporterImplPort();  
        
        {
        System.out.println("Invoking recibirActualizacionMandamientoInterInstitucional...");
        mx.gob.segob.nsjp.ws.cliente.recibiractualizacionmandamiento.MandamientoWSDTO _recibirActualizacionMandamientoInterInstitucional_arg0 = null;
        mx.gob.segob.nsjp.ws.cliente.recibiractualizacionmandamiento.DocumentoWSDTO _recibirActualizacionMandamientoInterInstitucional_arg1 = null;
        try {
            port.recibirActualizacionMandamientoInterInstitucional(_recibirActualizacionMandamientoInterInstitucional_arg0, _recibirActualizacionMandamientoInterInstitucional_arg1);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
