
package mx.gob.segob.nsjp.ws.cliente.respuestatranscripcion;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:57.515-05:00
 * Generated source version: 2.4.2
 * 
 */
public final class RegistrarTranscripcionAudienciaExporter_RegistrarTranscripcionAudienciaExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarTranscripcionAudienciaExporterImplService");

    private RegistrarTranscripcionAudienciaExporter_RegistrarTranscripcionAudienciaExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RegistrarTranscripcionAudienciaExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RegistrarTranscripcionAudienciaExporterImplService ss = new RegistrarTranscripcionAudienciaExporterImplService(wsdlURL, SERVICE_NAME);
        RegistrarTranscripcionAudienciaExporter port = ss.getRegistrarTranscripcionAudienciaExporterImplPort();  
        
        {
        System.out.println("Invoking registrarTranscripcionAudiencia...");
        java.lang.String _registrarTranscripcionAudiencia_arg0 = "";
        mx.gob.segob.nsjp.ws.cliente.respuestatranscripcion.DocumentoWSDTO _registrarTranscripcionAudiencia_arg1 = null;
        try {
            port.registrarTranscripcionAudiencia(_registrarTranscripcionAudiencia_arg0, _registrarTranscripcionAudiencia_arg1);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
