package mx.gob.segob.nsjp.ws.cliente.respuestatranscripcion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:57.625-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "RegistrarTranscripcionAudienciaExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/RegistrarTranscripcionAudienciaExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class RegistrarTranscripcionAudienciaExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarTranscripcionAudienciaExporterImplService");
    public final static QName RegistrarTranscripcionAudienciaExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarTranscripcionAudienciaExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/RegistrarTranscripcionAudienciaExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegistrarTranscripcionAudienciaExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/RegistrarTranscripcionAudienciaExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegistrarTranscripcionAudienciaExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistrarTranscripcionAudienciaExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrarTranscripcionAudienciaExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RegistrarTranscripcionAudienciaExporter
     */
    @WebEndpoint(name = "RegistrarTranscripcionAudienciaExporterImplPort")
    public RegistrarTranscripcionAudienciaExporter getRegistrarTranscripcionAudienciaExporterImplPort() {
        return super.getPort(RegistrarTranscripcionAudienciaExporterImplPort, RegistrarTranscripcionAudienciaExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrarTranscripcionAudienciaExporter
     */
    @WebEndpoint(name = "RegistrarTranscripcionAudienciaExporterImplPort")
    public RegistrarTranscripcionAudienciaExporter getRegistrarTranscripcionAudienciaExporterImplPort(WebServiceFeature... features) {
        return super.getPort(RegistrarTranscripcionAudienciaExporterImplPort, RegistrarTranscripcionAudienciaExporter.class, features);
    }

}
