package mx.gob.segob.nsjp.ws.cliente.notificacionaudiencia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-13T13:22:20.321-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "RecibirNotificacionAudienciaExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface RecibirNotificacionAudienciaExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/RecibirNotificacionAudienciaExporter/recibirNotificacionAudienciaRequest", output = "http://ws.service.nsjp.segob.gob.mx/RecibirNotificacionAudienciaExporter/recibirNotificacionAudienciaResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/RecibirNotificacionAudienciaExporter/recibirNotificacionAudiencia/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "recibirNotificacionAudiencia", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.notificacionaudiencia.RecibirNotificacionAudiencia")
    @WebMethod
    @ResponseWrapper(localName = "recibirNotificacionAudienciaResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.notificacionaudiencia.RecibirNotificacionAudienciaResponse")
    public java.lang.Boolean recibirNotificacionAudiencia(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.notificacionaudiencia.SolicitudAudienciaBasicoWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
