package mx.gob.segob.nsjp.ws.cliente.consultardistritos;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:13.758-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "ConsultarDistritosServiceWSExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultarDistritosServiceWSExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/ConsultarDistritosServiceWSExporter/consultarDistritosRequest", output = "http://ws.service.nsjp.segob.gob.mx/ConsultarDistritosServiceWSExporter/consultarDistritosResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/ConsultarDistritosServiceWSExporter/consultarDistritos/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "consultarDistritos", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.consultardistritos.ConsultarDistritos")
    @WebMethod
    @ResponseWrapper(localName = "consultarDistritosResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.consultardistritos.ConsultarDistritosResponse")
    public java.util.List<mx.gob.segob.nsjp.ws.cliente.consultardistritos.CatDistritoWSDTO> consultarDistritos() throws NSJPNegocioException_Exception;
}
