package mx.gob.segob.nsjp.ws.cliente.consultardistritos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:13.779-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "ConsultarDistritosServiceWSExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/ConsultarDistritosServiceWSExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class ConsultarDistritosServiceWSExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ConsultarDistritosServiceWSExporterImplService");
    public final static QName ConsultarDistritosServiceWSExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ConsultarDistritosServiceWSExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/ConsultarDistritosServiceWSExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultarDistritosServiceWSExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/ConsultarDistritosServiceWSExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultarDistritosServiceWSExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultarDistritosServiceWSExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarDistritosServiceWSExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ConsultarDistritosServiceWSExporter
     */
    @WebEndpoint(name = "ConsultarDistritosServiceWSExporterImplPort")
    public ConsultarDistritosServiceWSExporter getConsultarDistritosServiceWSExporterImplPort() {
        return super.getPort(ConsultarDistritosServiceWSExporterImplPort, ConsultarDistritosServiceWSExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarDistritosServiceWSExporter
     */
    @WebEndpoint(name = "ConsultarDistritosServiceWSExporterImplPort")
    public ConsultarDistritosServiceWSExporter getConsultarDistritosServiceWSExporterImplPort(WebServiceFeature... features) {
        return super.getPort(ConsultarDistritosServiceWSExporterImplPort, ConsultarDistritosServiceWSExporter.class, features);
    }

}
