package mx.gob.segob.nsjp.ws.cliente.solicitudcarpeta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:46:05.270-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "SolicitarCopiaCarpetaDeInvestigacionExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface SolicitarCopiaCarpetaDeInvestigacionExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/SolicitarCopiaCarpetaDeInvestigacionExporter/solicitarCopiaCarpetaDeInvestigacionRequest", output = "http://ws.service.nsjp.segob.gob.mx/SolicitarCopiaCarpetaDeInvestigacionExporter/solicitarCopiaCarpetaDeInvestigacionResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/SolicitarCopiaCarpetaDeInvestigacionExporter/solicitarCopiaCarpetaDeInvestigacion/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "solicitarCopiaCarpetaDeInvestigacion", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.solicitudcarpeta.SolicitarCopiaCarpetaDeInvestigacion")
    @WebMethod
    @ResponseWrapper(localName = "solicitarCopiaCarpetaDeInvestigacionResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.solicitudcarpeta.SolicitarCopiaCarpetaDeInvestigacionResponse")
    public mx.gob.segob.nsjp.ws.cliente.solicitudcarpeta.SolicitudAudienciaBasicoWSDTO solicitarCopiaCarpetaDeInvestigacion(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.solicitudcarpeta.SolicitudAudienciaBasicoWSDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Long arg1
    ) throws NSJPNegocioException_Exception;
}
