package mx.gob.segob.nsjp.ws.cliente.registarreplicacaso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:50.013-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "RegistrarReplicaCasoExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface RegistrarReplicaCasoExporter {

    @Action(input = "http://ws.service.nsjp.segob.gob.mx/RegistrarReplicaCasoExporter/registrarReplicaCasoRequest", output = "http://ws.service.nsjp.segob.gob.mx/RegistrarReplicaCasoExporter/registrarReplicaCasoResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/RegistrarReplicaCasoExporter/registrarReplicaCaso/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "registrarReplicaCaso", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.registarreplicacaso.RegistrarReplicaCaso")
    @WebMethod
    @ResponseWrapper(localName = "registrarReplicaCasoResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.registarreplicacaso.RegistrarReplicaCasoResponse")
    public void registrarReplicaCaso(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.registarreplicacaso.CasoWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
