package mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2012-06-08T17:04:00.842-05:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "PrincipalSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface PrincipalSoap {

    /**
     * Agenda una audiencia, y devuelve un identificador sobre el estado.
     */
    @WebResult(name = "agendar_AudienciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "agendar_Audiencia", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.AgendarAudiencia")
    @WebMethod(operationName = "agendar_Audiencia", action = "http://tempuri.org/agendar_Audiencia")
    @ResponseWrapper(localName = "agendar_AudienciaResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.AgendarAudienciaResponse")
    public int agendarAudiencia(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );

    /**
     * Método realizado para saber el estado de una audiencia.
     */
    @WebResult(name = "estado_AudienciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "estado_Audiencia", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.EstadoAudiencia")
    @WebMethod(operationName = "estado_Audiencia", action = "http://tempuri.org/estado_Audiencia")
    @ResponseWrapper(localName = "estado_AudienciaResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.EstadoAudienciaResponse")
    public int estadoAudiencia(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );

    /**
     * Listado de paths de archivos a transferir.
     */
    @WebResult(name = "ligas_PathResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ligas_Path", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.LigasPath")
    @WebMethod(operationName = "ligas_Path", action = "http://tempuri.org/ligas_Path")
    @ResponseWrapper(localName = "ligas_PathResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.LigasPathResponse")
    public java.lang.String ligasPath(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );

    /**
     * Archivo JVL asociado en formato byte[].
     */
    @WebResult(name = "generando_JVLResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "generando_JVL", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.GenerandoJVL")
    @WebMethod(operationName = "generando_JVL", action = "http://tempuri.org/generando_JVL")
    @ResponseWrapper(localName = "generando_JVLResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.GenerandoJVLResponse")
    public byte[] generandoJVL(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );

    /**
     * Consulta una audiencia y resolutivos, actualiza los datos de la audiencia y las notas realizadas.
     */
    @WebResult(name = "consultar_AudienciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "consultar_Audiencia", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.ConsultarAudiencia")
    @WebMethod(operationName = "consultar_Audiencia", action = "http://tempuri.org/consultar_Audiencia")
    @ResponseWrapper(localName = "consultar_AudienciaResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.ConsultarAudienciaResponse")
    public int consultarAudiencia(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );

    /**
     * Elimina todas las audiencias que compartan el ID 'audiencia_ID', y devuelve un identificador sobre el estado.
     */
    @WebResult(name = "eliminar_AudienciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "eliminar_Audiencia", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.EliminarAudiencia")
    @WebMethod(operationName = "eliminar_Audiencia", action = "http://tempuri.org/eliminar_Audiencia")
    @ResponseWrapper(localName = "eliminar_AudienciaResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.EliminarAudienciaResponse")
    public int eliminarAudiencia(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );

    /**
     * Consulta de cuantas audiencias relacionadas a un masterID están asociadas.
     */
    @WebResult(name = "hay_AudienciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "hay_Audiencia", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.HayAudiencia")
    @WebMethod(operationName = "hay_Audiencia", action = "http://tempuri.org/hay_Audiencia")
    @ResponseWrapper(localName = "hay_AudienciaResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.HayAudienciaResponse")
    public int hayAudiencia(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );

    /**
     * Archivo JVL asociado en formato cadena.
     */
    @WebResult(name = "generando_JVL_CadenaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "generando_JVL_Cadena", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.GenerandoJVLCadena")
    @WebMethod(operationName = "generando_JVL_Cadena", action = "http://tempuri.org/generando_JVL_Cadena")
    @ResponseWrapper(localName = "generando_JVL_CadenaResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.GenerandoJVLCadenaResponse")
    public java.lang.String generandoJVLCadena(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );

    /**
     * Archivo JVL asociado en formato cadena con paths.
     */
    @WebResult(name = "generando_JVL_PathsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "generando_JVL_Paths", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.GenerandoJVLPaths")
    @WebMethod(operationName = "generando_JVL_Paths", action = "http://tempuri.org/generando_JVL_Paths")
    @ResponseWrapper(localName = "generando_JVL_PathsResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.GenerandoJVLPathsResponse")
    public java.lang.String generandoJVLPaths(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );
}
