package mx.gob.segob.nsjp.ws.cliente.recibiracusederecibodesolicituddedefensor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:35.937-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService");
    public final static QName RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RecibirAcuseDeReciboDeSolicitudDeDefensorExporter
     */
    @WebEndpoint(name = "RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplPort")
    public RecibirAcuseDeReciboDeSolicitudDeDefensorExporter getRecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplPort() {
        return super.getPort(RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplPort, RecibirAcuseDeReciboDeSolicitudDeDefensorExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecibirAcuseDeReciboDeSolicitudDeDefensorExporter
     */
    @WebEndpoint(name = "RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplPort")
    public RecibirAcuseDeReciboDeSolicitudDeDefensorExporter getRecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplPort(WebServiceFeature... features) {
        return super.getPort(RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplPort, RecibirAcuseDeReciboDeSolicitudDeDefensorExporter.class, features);
    }

}
