
package mx.gob.segob.nsjp.ws.cliente.recibiracusederecibodesolicituddedefensor;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:35.821-05:00
 * Generated source version: 2.4.2
 * 
 */
public final class RecibirAcuseDeReciboDeSolicitudDeDefensorExporter_RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService");

    private RecibirAcuseDeReciboDeSolicitudDeDefensorExporter_RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService ss = new RecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplService(wsdlURL, SERVICE_NAME);
        RecibirAcuseDeReciboDeSolicitudDeDefensorExporter port = ss.getRecibirAcuseDeReciboDeSolicitudDeDefensorExporterImplPort();  
        
        {
        System.out.println("Invoking recibirAcuseDeReciboDeSolicitudDeDefensor...");
        mx.gob.segob.nsjp.ws.cliente.recibiracusederecibodesolicituddedefensor.SolicitudWSDTO _recibirAcuseDeReciboDeSolicitudDeDefensor_arg0 = null;
        mx.gob.segob.nsjp.ws.cliente.recibiracusederecibodesolicituddedefensor.DocumentoWSDTO _recibirAcuseDeReciboDeSolicitudDeDefensor_arg1 = null;
        try {
            mx.gob.segob.nsjp.ws.cliente.recibiracusederecibodesolicituddedefensor.DocumentoWSDTO _recibirAcuseDeReciboDeSolicitudDeDefensor__return = port.recibirAcuseDeReciboDeSolicitudDeDefensor(_recibirAcuseDeReciboDeSolicitudDeDefensor_arg0, _recibirAcuseDeReciboDeSolicitudDeDefensor_arg1);
            System.out.println("recibirAcuseDeReciboDeSolicitudDeDefensor.result=" + _recibirAcuseDeReciboDeSolicitudDeDefensor__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
