package mx.gob.segob.nsjp.ws.cliente.recibiracusederecibodesolicituddedefensor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:35.917-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "RecibirAcuseDeReciboDeSolicitudDeDefensorExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface RecibirAcuseDeReciboDeSolicitudDeDefensorExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/RecibirAcuseDeReciboDeSolicitudDeDefensorExporter/recibirAcuseDeReciboDeSolicitudDeDefensorRequest", output = "http://ws.service.nsjp.segob.gob.mx/RecibirAcuseDeReciboDeSolicitudDeDefensorExporter/recibirAcuseDeReciboDeSolicitudDeDefensorResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/RecibirAcuseDeReciboDeSolicitudDeDefensorExporter/recibirAcuseDeReciboDeSolicitudDeDefensor/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "recibirAcuseDeReciboDeSolicitudDeDefensor", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.recibiracusederecibodesolicituddedefensor.RecibirAcuseDeReciboDeSolicitudDeDefensor")
    @WebMethod
    @ResponseWrapper(localName = "recibirAcuseDeReciboDeSolicitudDeDefensorResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.recibiracusederecibodesolicituddedefensor.RecibirAcuseDeReciboDeSolicitudDeDefensorResponse")
    public mx.gob.segob.nsjp.ws.cliente.recibiracusederecibodesolicituddedefensor.DocumentoWSDTO recibirAcuseDeReciboDeSolicitudDeDefensor(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.recibiracusederecibodesolicituddedefensor.SolicitudWSDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.recibiracusederecibodesolicituddedefensor.DocumentoWSDTO arg1
    ) throws NSJPNegocioException_Exception;
}
