package mx.gob.segob.nsjp.ws.cliente.enviardocumentoainstitucion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:24.403-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "EnviarDocumentoAInstitucionExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface EnviarDocumentoAInstitucionExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/EnviarDocumentoAInstitucionExporter/enviarDocumentoAInstitucionRequest", output = "http://ws.service.nsjp.segob.gob.mx/EnviarDocumentoAInstitucionExporter/enviarDocumentoAInstitucionResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/EnviarDocumentoAInstitucionExporter/enviarDocumentoAInstitucion/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "enviarDocumentoAInstitucion", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.enviardocumentoainstitucion.EnviarDocumentoAInstitucion")
    @WebMethod
    @ResponseWrapper(localName = "enviarDocumentoAInstitucionResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.enviardocumentoainstitucion.EnviarDocumentoAInstitucionResponse")
    public java.lang.Long enviarDocumentoAInstitucion(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<mx.gob.segob.nsjp.ws.cliente.enviardocumentoainstitucion.DocumentoWSDTO> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws NSJPNegocioException_Exception;
}
