package mx.gob.segob.nsjp.ws.cliente.generaracuse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:33.469-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "GenerarAcuseDeReciboExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface GenerarAcuseDeReciboExporter {

    @Action(input = "http://ws.service.nsjp.segob.gob.mx/GenerarAcuseDeReciboExporter/generarAcuseDeReciboRequest", output = "http://ws.service.nsjp.segob.gob.mx/GenerarAcuseDeReciboExporter/generarAcuseDeReciboResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/GenerarAcuseDeReciboExporter/generarAcuseDeRecibo/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "generarAcuseDeRecibo", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.generaracuse.GenerarAcuseDeRecibo")
    @WebMethod
    @ResponseWrapper(localName = "generarAcuseDeReciboResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.generaracuse.GenerarAcuseDeReciboResponse")
    public void generarAcuseDeRecibo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws NSJPNegocioException_Exception;
}
