package mx.gob.segob.nsjp.ws.cliente.generaracuse;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:33.490-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "GenerarAcuseDeReciboExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/GenerarAcuseDeReciboExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class GenerarAcuseDeReciboExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "GenerarAcuseDeReciboExporterImplService");
    public final static QName GenerarAcuseDeReciboExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "GenerarAcuseDeReciboExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/GenerarAcuseDeReciboExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GenerarAcuseDeReciboExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/GenerarAcuseDeReciboExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GenerarAcuseDeReciboExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GenerarAcuseDeReciboExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenerarAcuseDeReciboExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GenerarAcuseDeReciboExporter
     */
    @WebEndpoint(name = "GenerarAcuseDeReciboExporterImplPort")
    public GenerarAcuseDeReciboExporter getGenerarAcuseDeReciboExporterImplPort() {
        return super.getPort(GenerarAcuseDeReciboExporterImplPort, GenerarAcuseDeReciboExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenerarAcuseDeReciboExporter
     */
    @WebEndpoint(name = "GenerarAcuseDeReciboExporterImplPort")
    public GenerarAcuseDeReciboExporter getGenerarAcuseDeReciboExporterImplPort(WebServiceFeature... features) {
        return super.getPort(GenerarAcuseDeReciboExporterImplPort, GenerarAcuseDeReciboExporter.class, features);
    }

}
