package mx.gob.segob.nsjp.ws.cliente.actualizacionsentencia;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:03.943-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "ActualizacionSentenciaExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/ActualizacionSentenciaExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class ActualizacionSentenciaExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ActualizacionSentenciaExporterImplService");
    public final static QName ActualizacionSentenciaExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ActualizacionSentenciaExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/ActualizacionSentenciaExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ActualizacionSentenciaExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/ActualizacionSentenciaExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ActualizacionSentenciaExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ActualizacionSentenciaExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActualizacionSentenciaExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ActualizacionSentenciaExporter
     */
    @WebEndpoint(name = "ActualizacionSentenciaExporterImplPort")
    public ActualizacionSentenciaExporter getActualizacionSentenciaExporterImplPort() {
        return super.getPort(ActualizacionSentenciaExporterImplPort, ActualizacionSentenciaExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ActualizacionSentenciaExporter
     */
    @WebEndpoint(name = "ActualizacionSentenciaExporterImplPort")
    public ActualizacionSentenciaExporter getActualizacionSentenciaExporterImplPort(WebServiceFeature... features) {
        return super.getPort(ActualizacionSentenciaExporterImplPort, ActualizacionSentenciaExporter.class, features);
    }

}
