package mx.gob.segob.nsjp.ws.cliente.actualizacionsentencia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:03.934-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "ActualizacionSentenciaExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface ActualizacionSentenciaExporter {

    @Action(input = "http://ws.service.nsjp.segob.gob.mx/ActualizacionSentenciaExporter/actualizarSentenciaRequest", output = "http://ws.service.nsjp.segob.gob.mx/ActualizacionSentenciaExporter/actualizarSentenciaResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/ActualizacionSentenciaExporter/actualizarSentencia/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "actualizarSentencia", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.actualizacionsentencia.ActualizarSentencia")
    @WebMethod
    @ResponseWrapper(localName = "actualizarSentenciaResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.actualizacionsentencia.ActualizarSentenciaResponse")
    public void actualizarSentencia(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.actualizacionsentencia.SentenciaWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
