package mx.gob.segob.nsjp.ws.cliente.enviarcarpetainvestigacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:22.585-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "EnviarCarpetaDeInvestigacionExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface EnviarCarpetaDeInvestigacionExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/EnviarCarpetaDeInvestigacionExporter/enviarCarpetaDeInvestigacionRequest", output = "http://ws.service.nsjp.segob.gob.mx/EnviarCarpetaDeInvestigacionExporter/enviarCarpetaDeInvestigacionResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/EnviarCarpetaDeInvestigacionExporter/enviarCarpetaDeInvestigacion/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "enviarCarpetaDeInvestigacion", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.enviarcarpetainvestigacion.EnviarCarpetaDeInvestigacion")
    @WebMethod
    @ResponseWrapper(localName = "enviarCarpetaDeInvestigacionResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.enviarcarpetainvestigacion.EnviarCarpetaDeInvestigacionResponse")
    public java.lang.Long enviarCarpetaDeInvestigacion(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.enviarcarpetainvestigacion.ExpedienteWSDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws NSJPNegocioException_Exception;
}
