package mx.gob.segob.nsjp.ws.cliente.medidaalterna;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:46.111-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "RegistrarMedidaAlternaServiceExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface RegistrarMedidaAlternaServiceExporter {

    @Action(input = "http://ws.service.nsjp.segob.gob.mx/RegistrarMedidaAlternaServiceExporter/registrarMedidaAlternaRequest", output = "http://ws.service.nsjp.segob.gob.mx/RegistrarMedidaAlternaServiceExporter/registrarMedidaAlternaResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/RegistrarMedidaAlternaServiceExporter/registrarMedidaAlterna/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "registrarMedidaAlterna", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.medidaalterna.RegistrarMedidaAlterna")
    @WebMethod
    @ResponseWrapper(localName = "registrarMedidaAlternaResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.medidaalterna.RegistrarMedidaAlternaResponse")
    public void registrarMedidaAlterna(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.medidaalterna.MedidaAlternaWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
