package mx.gob.segob.nsjp.ws.cliente.enviarinformepolicialhomologado;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:28.773-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "EnviarInformePolicialHomologadoExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/EnviarInformePolicialHomologadoExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class EnviarInformePolicialHomologadoExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "EnviarInformePolicialHomologadoExporterImplService");
    public final static QName EnviarInformePolicialHomologadoExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "EnviarInformePolicialHomologadoExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/EnviarInformePolicialHomologadoExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EnviarInformePolicialHomologadoExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/EnviarInformePolicialHomologadoExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EnviarInformePolicialHomologadoExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EnviarInformePolicialHomologadoExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnviarInformePolicialHomologadoExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns EnviarInformePolicialHomologadoExporter
     */
    @WebEndpoint(name = "EnviarInformePolicialHomologadoExporterImplPort")
    public EnviarInformePolicialHomologadoExporter getEnviarInformePolicialHomologadoExporterImplPort() {
        return super.getPort(EnviarInformePolicialHomologadoExporterImplPort, EnviarInformePolicialHomologadoExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnviarInformePolicialHomologadoExporter
     */
    @WebEndpoint(name = "EnviarInformePolicialHomologadoExporterImplPort")
    public EnviarInformePolicialHomologadoExporter getEnviarInformePolicialHomologadoExporterImplPort(WebServiceFeature... features) {
        return super.getPort(EnviarInformePolicialHomologadoExporterImplPort, EnviarInformePolicialHomologadoExporter.class, features);
    }

}
