package mx.gob.segob.nsjp.ws.cliente.solicitudaudiencia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:46:02.687-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "SolicitarAudienciaBasicoExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface SolicitarAudienciaBasicoExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/SolicitarAudienciaBasicoExporter/registrarSolicitudAudienciaBasicoRequest", output = "http://ws.service.nsjp.segob.gob.mx/SolicitarAudienciaBasicoExporter/registrarSolicitudAudienciaBasicoResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/SolicitarAudienciaBasicoExporter/registrarSolicitudAudienciaBasico/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "registrarSolicitudAudienciaBasico", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.solicitudaudiencia.RegistrarSolicitudAudienciaBasico")
    @WebMethod
    @ResponseWrapper(localName = "registrarSolicitudAudienciaBasicoResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.solicitudaudiencia.RegistrarSolicitudAudienciaBasicoResponse")
    public java.lang.Long registrarSolicitudAudienciaBasico(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.solicitudaudiencia.SolicitudAudienciaBasicoWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
