package mx.gob.segob.nsjp.ws.cliente.solicitudaudiencia;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:46:02.699-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "SolicitarAudienciaBasicoExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/SolicitarAudienciaBasicoExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class SolicitarAudienciaBasicoExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "SolicitarAudienciaBasicoExporterImplService");
    public final static QName SolicitarAudienciaBasicoExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "SolicitarAudienciaBasicoExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/SolicitarAudienciaBasicoExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SolicitarAudienciaBasicoExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/SolicitarAudienciaBasicoExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SolicitarAudienciaBasicoExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SolicitarAudienciaBasicoExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SolicitarAudienciaBasicoExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SolicitarAudienciaBasicoExporter
     */
    @WebEndpoint(name = "SolicitarAudienciaBasicoExporterImplPort")
    public SolicitarAudienciaBasicoExporter getSolicitarAudienciaBasicoExporterImplPort() {
        return super.getPort(SolicitarAudienciaBasicoExporterImplPort, SolicitarAudienciaBasicoExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SolicitarAudienciaBasicoExporter
     */
    @WebEndpoint(name = "SolicitarAudienciaBasicoExporterImplPort")
    public SolicitarAudienciaBasicoExporter getSolicitarAudienciaBasicoExporterImplPort(WebServiceFeature... features) {
        return super.getPort(SolicitarAudienciaBasicoExporterImplPort, SolicitarAudienciaBasicoExporter.class, features);
    }

}
