/**
 * Nombre del Programa : Actividades.java
 * Autor                            : vaguirre
 * Compania                    : Ultrasist
 * Proyecto                      : NSJP                    Fecha: 12 May 2011
 * Marca de cambio        : N/A
 * Descripcion General    : Enumaraci�n para las actividades
 * Programa Dependiente  :N/A
 * Programa Subsecuente :N/A
 * Cond. de ejecucion        :N/A
 * Dias de ejecucion          :N/A                             Horario: N/A
 *                              MODIFICACIONES
 *------------------------------------------------------------------------------
 * Autor                       :N/A
 * Compania               :N/A
 * Proyecto                 :N/A                                 Fecha: N/A
 * Modificacion           :N/A
 *------------------------------------------------------------------------------
 */
package mx.gob.segob.nsjp.comun.enums.actividad;

import java.util.HashMap;
import java.util.Map;

/**
 * Enumaraci�n para las actividades.
 * 
 * @version 1.0
 * @author vaguirre
 * 
 */
public enum Actividades {
	
	 //Actuacion para Merida
	COMPARECENCIA_PARA_OTORGAR_PERDON_18_A(553L),
	ARCHIVO_DEFINITIVO_18_B(555L),
	OFICIO_PARA_CANALIZAR_A_MEDIACION(559L),
    CIERRE_DE_INVESTIGACION(557L),
    
	/**
     * <b>Generar denuncia</b> es la unica actividad que debe generar un
     * expediente maestro, las restantes si lo pueden generar un numero.
     */
    GENERAR_DENUNCIA_EN_ATP(1647L),
    GENERAR_DENUNCIA_EN_PM(6904L),
    //
    SOLICITAR_APOYO_UNIDAD_ATENCION_VICTIMAS(1648L), CANALIZAR_JUSTICIA_ALTERNATIVA_RESTAURATIVA(
            1649L), CANALIZAR_UNIDAD_INVESTIGACION(1650L),
    // TODO TERMINAR LIMITE 1698
    CAPTURAR_ENTREVISTA_INICIAL(1651L), GENERAR_INVITACION(1652L), CAPTURAR_ENTREVISTA_COMPLEMENTARIA(
            1653L), GENERAR_ACUERDO(1654L), GENERAR_ACTA_DE_AUDIENCIA(2044L), ELABORAR_TRANSCRIPCION_DE_AUDIENCIA(2045L),
            RECIBIR_CANALIZACION_UI(2133L), RECIBIR_CANALIZACION_JAR(2135L), ATENDER_CANALIZACION_UI(2134L), 
            ATENDER_CANALIZACION_JAR(2290L), GENERAR_CEDULA_DE_IDENTIFICACION(2192L),
            GENERAR_OFICIO_DE_SOLICITUD_DE_ATENCION_PSICOLOGICA_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(2237L),
            SOLICITAR_ATENCION_PSICOLOGICA_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(2254L),
            GENERAR_OFICIO_DE_SOLICITUD_DE_ATENCION_MEDICA_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(2236L),
            SOLICITAR_ATENCION_MEDICA_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(2286L),
            GENERAR_OFICIO_DE_SOLICITUD_DE_ASESORIA_JURIDICA_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(2235L),
            SOLICITAR_ORIENTACION_LEGAL_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(2259L),
            GENERAR_OFICIO_DE_SOLICITUD_DE_SEGURIDAD_POLICIAL_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(2238L),
            SOLICITAR_SEGURIDAD_POLICIAL_A_LA_DIRECCION_DE_ATENCION_A_VICTIMAS(2260L),
            ADJUNTAR_ARCHIVO_DIGITAL(2197L),
            GENERAR_QUERELLA(2242L),
            CAPTURAR_DECLARACION(2206L),
            DIRIGIR_A_INSTANCIA_EXTERNA(2210L),
            DIRIGIR_A_LA_UNIDAD_DE_SOLUCION_DE_CONTROVERSIAS(2287L),
            DIRIGIR_A_LA_UNIDAD_DE_FISCALES_INVESTIGADORES(2288L),
            AVISAR_QUE_LA_DENUNCIA_O_QUERELLA_SE_DIRIGIO_A_LA_UNIDAD_DE_MEDIOS_ALTERNOS_DE_SOLUCION_DE_CONTROVERSIAS(2289L),
            AVISAR_A_LA_UNIDAD_DE_FISCALES_INVESTIGADORES_DEL_NO_CUMPLIMIENTO_DEL_ACUERDO(2203L),
            GENERAR_CONSTANCIA_DE_FALTA_DE_INTERES(2229L),
            GENERAR_CITATORIO_PARA_VICTIMA(2228L),
            GENERAR_CITATORIO_PARA_EL_PROBABLE_RESPONSABLE(2227L),
            ACEPTACION_DEL_SERVICIO_POR_PARTE_DE_LA_VICTIMA(2195L),
            ACEPTACION_DEL_SERVICIO_POR_PARTE_DEL_INVITADO(2196L),
            LLEVAR_A_CABO_LA_AUDIENCIA_DE_CONCILIACION_MEDIACION(2248L),
            GENERAR_CONVENIO_DE_CONCILIACION_MEDIACION(2231L),
            AVISAR_DE_CONVENIO_AL_FISCAL_DE_LA_UNIDAD_DE_FISCALES_INVESTIGADORES(2249L),
            GENERAR_CONSTANCIA_DE_SEGUIMIENTO_A_CONVENIO(2230L),
            ELABORAR_CARTA_DE_CUMPLIMIENTO_DE_ACUERDO(2211L),
            ELABORAR_CARTA_DE_FELICITACION(2212L),
            AVISAR_A_LA_UNIDAD_DE_FISCALES_INVESTIGADORES_DEL_CUMPLIMIENTO_DEL_ACUERDO(2202L),
            DETERMINAR_NO_INICIO_DE_INVESTIGACION(2208L),
            REGRESAR_A_UNIDAD_DE_SOLUCION_DE_CONTROVERSIAS(2253L),
            GENERAR_AVISO_DE_LA_DETENCION_A_LA_DEFENSORIA(2232L),
            DICTAR_ACUERDO_DE_RETENCION(2209L),
            ELABORAR_OFICIO_INVESTIGACION_POLICIAL(2222L),
            ELABORAR_OFICIO_INVESTIGACION_POLICIACA(2221L),
            ELABORAR_OFICIO_DE_SOLICITUD_DE_DILIGENCIAS_MINISTERIALES(2217L),
            ELABORAR_OFICIO_DE_SOLICITUD_DE_DICTAMENES_PERICIALES(2216L),
            SOLICITAR_DILIGENCIAS_MINISTERIALES(2292L),
            SOLICITAR_DICTAMENES_PERICIALES(2291L),
            ELABORAR_OFICIO_DE_SOLICITUD_DE_ORDEN_DE_APREHENSION(2218L),
            SOLICITAR_ORDEN_DE_APREHENSION(2257L),
            ELABORAR_OFICIO_DE_SOLICITUD_DE_ORDEN_DE_CATEO(2219L),
            SOLICITAR_ORDEN_DE_CATEO(2258L),
            ELABORAR_OFICIO_PARA_INTERVENCION_DE_COMUNICACIONES(2224L),
            ELABORAR_OFICIO_ORDENANDO_FIJACION_Y_PRESERVACION_DEL_LUGAR_DE_LOS_HECHOS_Y_DEL_HALLAZGO(2223L),
            ASENTAR_REGISTRO_DE_CADENA_DE_CUSTODIA_RCC(2200L),
            INGRESAR_EVIDENCIA_A_CADENA_DE_CUSTODIA(2247L),
            REGISTRAR_ESLABONES_DE_CADENA_DE_CUSTODIA(2252L),
            ORDENAR_REPARACION_DEL_DANO(2250L),
            GENERAR_DICTAMEN_MOTIVADO_DE_CRITERIO_DE_OPORTUNIDAD(2244L),
            GENERAR_RAZONES_PARA_CRITERIO_DE_OPORTUNIDAD(2245L),
            INFORMAR_A_PROCURADOR_GENERAL_LA_APLICACION_DE_CRITERIO(2246L),
            ARCHIVO_TEMPORAL(2199L),
            TURNA_A_SU_SUPERIOR_JERARQUICO_DECISION_DE_REAPERTURA_DEL_ARCHIVO(2262L),
            PROMOVER_RECURSOS(2251L),
            ARCHIVO_DEFINITIVO(2198L),
            GENERAR_OFICIO_A_POLICIA_PARA_LLEVAR_A_CABO_LA_DESTRUCCION_DE_LOS_OBJETOS(2234L),
            GENERAR_OFICIO_A_PERITOS_PARA_LLEVAR_A_CABO_LA_DESTRUCCION_DE_LOS_OBJETOS(2233L),
            GENERAR_ACTA_DE_DESTRUCCION(2226L),
            GENERAR_OFICIO_PARA_NOTIFICAR_AL_PROPIETARIO_DE_LA_DEVOLUCION_DEL_OBJETO(2240L),
            GENERAR_OFICIO_PARA_EL_ASEGURAMIENTO_Y_RESGUARDO_DEL_LUGAR(2239L),
            GENERAR_OFICIO_PARA_REGISTROS_PUBLICOS(2241L),
            COMPARTIR_CARPETA_DE_INVESTIGACION(2207L),
            ELABORAR_OFICIO_DE_SOLICITUD_DE_AUDIENCIA_DE_CONTROL_JUDICIAL(2214L),
            GENERAR_SOLICITUD_DE_AUDIENCIA_DE_CONTROL_JUDICIAL(2243L),
            ELABORAR_OFICIO_DE_SOLICITUD_DE_AUDIENCIA(2213L),
            SOLICITAR_AUDIENCIA(2255L),
            ELABORAR_OFICIO_DE_SOLICITUD_DE_TRANSCRIPCION_DE_AUDIENCIA(2220L),
            SOLICITAR_TRANSCRIPCION_DE_AUDIENCIA(2261L),
            SOLICITAR_COPIA_DE_AUDIO_Y_VIDEO_DE_AUDIENCIA(2256L),
            ELABORAR_OFICIO_DE_SOLICITUD_DE_COPIA_DE_AUDIO_Y_VIDEO_DE_AUDIENCIA(2215L),
            SOLICITAR_SERVICIO_PERICIAL(2408L),
            GENERAR_ACUERDO_DE_DEFENSA(2193L), 
            GENERAR_LIBRO_DE_GOBIERNO(2481L), 
            VINCULAR_EXPEDIENTE_A_CASO(2482L), 
            SOLICITAR_CARPETA_DE_INVESTIGACION(2483L),
            REACTIVAR_ARCHIVO_TEMPORAL(2498L),
            NO_ACEPTACION_DEL_SERVICIO_POR_PARTE_DEL_INVITADO(2499L),
            GENERAR_ACUSE_ATENCION_CIUDADADA_DEFENSORIA(2521L),
            SOLICITAR_ASESORIA_LEGAL(2580L),ADJUNTAR_ACUERDO_RESTAURATIVO(2522L),
            GENERAR_ACUERDO_CON_AMP(1656L), NOTIFICAR_AUDITORIA(2757L),
            ASIGNAR_SOLICITUD_DE_AYUDA(2936L),
            SEGUIMIENTO_A_ESTUDIO_SOCIOECONOMICO(2937L),
            ENVIAR_ESTUDIO_SOCIOECONOMICO(2938L),
            PROPORCIONAR_APOYO_LEGAL(2900L),
            ASESORIA_LEGAL_A_VICTIMA(2939L),
            //USADA PARA ADMINAT
            GENERAR_SOLICITUD_DE_DICTAMEN_MEDICO_DE_LESIONES(4417L),
    
            //USADAS PARA EL SISTEMA TRADICIONAL
    		RESERVA(257L),
    		RESERVA_ACTIVA(259L),
    		GENERAR_ACUERDO_DE_REAPERTURA_DEL_CASO(2496L),
    		GENERAR_OFICIO_DE_SOLICITUD_PARA_PERICIALES(2961L),
    		GENERAR_OFICIO_PARA_REACTIVAR_INVESTIGACION(2807L),
    		APREHENSION(261L),
    		SOLICITUD_DE_ORDEN_DE_CATEO(263L),
    		TURNA_A_SU_SUPERIOR_JERARQUICO_DECISION_DE_REAPERTURA_DEL_EXPEDIENTE(265L),
    		GENERAR_ACTAS(267L),
    		GENERAR_CONSTANCIA(269L),
    		GENERAR_FE(271L),
    		GENERAR_RAZON(275L),
    		GENERAR_PLIEGO_DE_CONSIGNACION(277L),
    		REGISTRAR_AMPARO(300L),
    
    		//USADAS PARA UAVD PSICOLOGICO
    		SUSPENDER_AYUDA(2901L),
    		CONCLUIR_SATISFACTORIAMENTE(2902L),
    		REINICIAR_AYUDA(2903L),
    
    		//USADAS PARA ATENCION ADMINISTRATIVA
    		SOLICITAR_ATENCION_PSICOLOGICA(302L),
    		SOLICITAR_ANTENCION_MEDICA(304L),
    		SOLICITAR_ATENCION_DE_TRABAJO_SOCIAL(306L),
    		ANEXAR_DOCUMENTO(3555L),
    		
    		//Usadas para alerts de cambio de estado del expediente
    		GENERAR_CONSTANCIA_DE_TERMINACION_DEL_PROCEDIMIENTO(3708L),
    		DIRIGIR_A_ATENCION_TEMPRANA_PENAL(3998L),SOLICITAR_DEFENSOR(4200L),
    
    		//USADAS PARA CONSIGNADOR
    		DETERMINAR_LA_FALTA_DE_DILIGENCIAS(4254L),
    		DETERMINAR_LA_FALTA_DE_RESPUESTAS_A_PARTICULARES(4256L),
    		DETERMINAR_NEAP(4258L),
    		GENERAR_OFICIO_DE_CONSIGNACION(4260L),
    		
    		//USUADAS PARA PERICIALES - PERITO
    		ANEXAR_DOCUMENTO_PERITO(278L),
    		REALIZAR_DICTAMEN(279L),
    		REALIZAR_INFORME(280L),
    		SOLICITUD_DE_EVIDENCIA(281L),
    		DEVOLUCION_EVIDENCIA(282L),
    		OFICIO_DE_DESTRUCCION(283L),
    		SOLICITUD_DE_AMPLIACION_DE_PERIODO(284L),
	
			//Utilizadas dentro de reinserción social
    		GENERAR_ACUSE_RECIBO_PERTENENCIAS(6349L),
			GENERAR_OFICIO_DE_INGRESO_A_REINSERCION_SOCIAL(410L),
			ELABORAR_CERTIFICADO_PSICOFISICO(376L),
			ELABORAR_CERTIFICADO_DE_LESIONES(378L),
			ELABORAR_CERTIFICADO_QUIMICO(380L),
			ELABORAR_INFORME_FINAL_DE_REINSERCION_SOCIAL_DEL_SENTENCIADO(408L),
			AVISAR_DE_INGRESO_A_CERESO(372L),
			ELABORAR_CERTIFICADO_DE_LIBERACION(366L),
			ENTREGAR_VALORES_Y_EFECTOS_DEPOSITADOS(6548L),
			GENERAR_RESUMEN_PUNTOS_RECOMPENSAS(6895L),
			GENERAR_PLAN_REINSERCION_SOCIAL(6340L),
			GENERAR_ACUERDO_DE_RECHAZO_DE_REINSERCION_SOCIAL(6900L),
			GENERAR_ACUERDO_DE_AUTORIZACION_DE_REINSERCION_SOCIAL(6898L),
			//Para mandamientos judiciales y medida cautelares
			GENERAR_MEDIDA_CAUTELAR(6376L),
			GENERAR_MANDAMIENTO_JUDICIAL(6374L),
			GENERAR_DOCUMENTO_DE_CAMBIO_DE_ESTATUS_DE_MEDIDA_CAUTELAR(6380L),
			GENERAR_DOCUMENTO_DE_CAMBIO_DE_ESTATUS_DE_MANDAMIENTO_JUDICIAL(6378L),
			GENARAR_INFORME_DE_LINEA_DE_INVESTIGACION(7072L),
			SOLICITAR_DEFENSOR_PUBLICO(7074L),
			ADJUNTAR_AUTO_DE_PROCEDIMIENTO_DE_EJECUCION(7080L),
			ADJUNTAR_SENTENCIA_EJECUTORIADA(7082L),
			GENERAR_ACUSE_DE_RECIBO_DE_SOLICITUD_DE_DEFENSOR_PUBLICO(7076L),
			ELABORAR_ACUERDO_RECEPCION_SENTENCIA(7086L),
			SOLICITAR_CONSTANCIAS_CERERESO(7089L),
			SOLICITAR_ESTUDIOS_CTI(7092L),
			ELABORAR_SOLICITUD_REMISION_PARCIAL_PENA(358L),
			ELABORAR_SOLICITUD_LIBERTAD_CONDICIONAL(7136L),
			ELABORAR_SOLICITUD_PRELIBERTAD(7138L),
			ELABORAR_SOLICITUD_INDULTO(7140L),
			ELABORAR_SOLICITUD_REPARACION_DANIO(7142L),
			ELABORAR_SOLICITUD_VISITA_CONYUGAL(7144L),
			GENERAR_ACUSE_DE_RECIBO_DE_CARPETA_DE_INVESTIGACION(7477L),
			RECIBIR_ACUSE_DE_RECIBO_DE_CARPETA_DE_INVESTIGACION(7480L),
			GENERAR_ACUERDO_DE_AUTORIZACION_DE_REMISION_PARCIAL_PENA(7152L),
			GENERAR_ACUERDO_DE_RECHAZO_DE_REMISION_PARCIAL_PENA(7154L),
			ELABORAR_SOLICITUD_DECLARACION_JUDICIAL_EXTINCION_PRISION(7158L),
			ELABORAR_SOLICITUD_PRESCRIPCION_PENA_PRISION(7160L),
			ELABORAR_SOLICITUD_CERTIFICADO_EXTINCION_PENAS_PRISION(7162L),
			ELABORAR_SOLICITUD_PROCEDIMIENTO_EXTINCION_MULTA(7164L),
			ELABORAR_SOLICITUD_PROCEDIMIENTO_EXTINCION_REPARACION_DANIO(7166L),
			ELABORAR_SOLICITUD_CERTIFICADO_EXTINCION_PENAS_PECUNIARIAS(7168L),
			ELABORAR_SOLICITUD_AUTO_FINALIZACION_PROCEDIMIENTO_EJECUCION(7170L),
			GENERAR_ACUERDO_AUTORIZACION_DECLARACION_JUDICIAL_EXTINCION_PRISION(7179L),
			GENERAR_ACUERDO_RECHAZO_DECLARACION_JUDICIAL_EXTINCION_PRISION(7181L),
			GENERAR_ACUERDO_AUTORIZACION_LIBERTAD_CONDICIONAL(7447L),
			GENERAR_ACUERDO_RECHAZO_LIBERTAD_CONDICIONAL(7449L),
			GENERAR_ACUERDO_AUTORIZACION_PRELIBERTAD(7453L),
			GENERAR_ACUERDO_RECHAZO_PRELIBERTAD(7455L),
			GENERAR_ACUERDO_AUTORIZACION_INDULTO(7459L),
			GENERAR_ACUERDO_RECHAZO_INDULTO(7461L),
			GENERAR_ACUERDO_AUTORIZACION_REPARACION_DANIO(7465L),
			GENERAR_ACUERDO_RECHAZO_REPARACION_DANIO(7467L),
			GENERAR_ACUERDO_AUTORIZACION_VISITA_CONYUGAL(7471L),
			GENERAR_ACUERDO_RECHAZO_VISITA_CONYUGAL(7473L),
			GENERAR_ACUERDO_AUTORIZACION_EXTINCION_MULTA(7483L),
			GENERAR_ACUERDO_RECHAZO_EXTINCION_MULTA(7485L),
			GENERAR_ACUERDO_AUTORIZACION_EXTINCION_REPARACION_DANIO(7489L),
			GENERAR_ACUERDO_RECHAZO_EXTINCION_REPARACION_DANIO(7491L),
			ELABORAR_SOLICITUD_INFORMACION_DGPRS(7495L),
			COMUNICAR_ACUERDO_RESOLUCION_DGPRS(7497L), 
			ELABORAR_ACUERDO_CANCELACION_INICIO_PROCEDIMIENTO_EJECUCION(7503L),
			INFORMAR_INTEGRACION_PROCEDIMIENTO_EJECUCION(7569L),
			REGISTRAR_ACUERDO_PROCEDIMIENTO_EJECUCION(7571L),
			//Actividad Especifica para el peritoMP en el cual se regresa la solicitud a un estatus en el ke se necesitn mas fundamentos por parte del amp 
			SOLICITAR_MAS_INFORMACION_DICTAMEN(7591L),
			ELABORAR_OFICIO_CUMPLIMIENTO_MANDAMIENTO_JUDICIAL(7575L),
			REPORTE_CUMPLIMIENTO_MANDAMIENTO_JUDICIAL(7636L),
			ELABORAR_ACUERDO_DE_ABSTENCION(6265L),
            DIRIGIR_A_LA_UNIDAD_DE_SOLUCION_DE_CONTROVERSIAS_SIN_SUSPENDER_EXPEDIENTE(9795L),
            GENERAR_DETERMINACION_DE_ARCHIVO_TEMPORAL_CON_IMPUTADO_DESCONOCIDO(6397L),
            SEGUIMIENTO_A_OFICIO_DE_CUMPLIMIENTO_DE_MANDAMIENTO_JUDICIAL(9842L),
            //Nueva funcionalidad de Exhortos
			GENERAR_EXHORTO_PJ(30011L),
			REPORTE_ORDENES_DE_APREHENSION_CUMPLIDAS(30682L),
			CONCLUSION_POR_VISTA_DE_NO_EJERCICIO(30683L),
			CONCLUSION_POR_REPARACION_DEL_DANO(30684L);
    		
    
    private Long valorId;
    
    private final static Map<Long, Actividades> HASH = new HashMap<Long, Actividades>();

    static {
        Actividades[] acts = Actividades.values();
        int pos = 0;
        while (pos < acts.length) {
            HASH.put(acts[pos].getValorId(), acts[pos]);
            pos++;
        }
    }
    private Actividades(Long valorIdPredefinido) {
        this.valorId = valorIdPredefinido;
    }

    public static Actividades getByValor(Long valorIdPredefinido) {
        return HASH.get(valorIdPredefinido);
    }

    /**
     * M&eacute;todo de acceso al campo valorId.
     * 
     * @return El valor del campo valorId asociado en le BD.
     */
    public Long getValorId() {
        return valorId;
    }
}
