package mx.gob.segob.nsjp.ws.cliente.consultarfuncionarioexterno;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:16.321-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "ConsultarFuncionarioExternoExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultarFuncionarioExternoExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/ConsultarFuncionarioExternoExporter/consultarFuncionariosXCriterioRequest", output = "http://ws.service.nsjp.segob.gob.mx/ConsultarFuncionarioExternoExporter/consultarFuncionariosXCriterioResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/ConsultarFuncionarioExternoExporter/consultarFuncionariosXCriterio/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "consultarFuncionariosXCriterio", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.consultarfuncionarioexterno.ConsultarFuncionariosXCriterio")
    @WebMethod
    @ResponseWrapper(localName = "consultarFuncionariosXCriterioResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.consultarfuncionarioexterno.ConsultarFuncionariosXCriterioResponse")
    public java.util.List<mx.gob.segob.nsjp.ws.cliente.consultarfuncionarioexterno.FuncionarioWSDTO> consultarFuncionariosXCriterio(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.consultarfuncionarioexterno.CriterioConsultaFuncionarioExternoWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
