package mx.gob.segob.nsjp.ws.cliente.estatusmandamiento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:06.169-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "ActualizarEstatusMandamientoInstitucionalExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/ActualizarEstatusMandamientoInstitucionalExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class ActualizarEstatusMandamientoInstitucionalExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ActualizarEstatusMandamientoInstitucionalExporterImplService");
    public final static QName ActualizarEstatusMandamientoInstitucionalExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ActualizarEstatusMandamientoInstitucionalExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/ActualizarEstatusMandamientoInstitucionalExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ActualizarEstatusMandamientoInstitucionalExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/ActualizarEstatusMandamientoInstitucionalExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ActualizarEstatusMandamientoInstitucionalExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ActualizarEstatusMandamientoInstitucionalExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActualizarEstatusMandamientoInstitucionalExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ActualizarEstatusMandamientoInstitucionalExporter
     */
    @WebEndpoint(name = "ActualizarEstatusMandamientoInstitucionalExporterImplPort")
    public ActualizarEstatusMandamientoInstitucionalExporter getActualizarEstatusMandamientoInstitucionalExporterImplPort() {
        return super.getPort(ActualizarEstatusMandamientoInstitucionalExporterImplPort, ActualizarEstatusMandamientoInstitucionalExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ActualizarEstatusMandamientoInstitucionalExporter
     */
    @WebEndpoint(name = "ActualizarEstatusMandamientoInstitucionalExporterImplPort")
    public ActualizarEstatusMandamientoInstitucionalExporter getActualizarEstatusMandamientoInstitucionalExporterImplPort(WebServiceFeature... features) {
        return super.getPort(ActualizarEstatusMandamientoInstitucionalExporterImplPort, ActualizarEstatusMandamientoInstitucionalExporter.class, features);
    }

}
