package mx.gob.segob.nsjp.ws.cliente.estatusmandamiento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:06.158-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "ActualizarEstatusMandamientoInstitucionalExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface ActualizarEstatusMandamientoInstitucionalExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/ActualizarEstatusMandamientoInstitucionalExporter/actualizarEstatusMandamientoJudicialRequest", output = "http://ws.service.nsjp.segob.gob.mx/ActualizarEstatusMandamientoInstitucionalExporter/actualizarEstatusMandamientoJudicialResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/ActualizarEstatusMandamientoInstitucionalExporter/actualizarEstatusMandamientoJudicial/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "actualizarEstatusMandamientoJudicial", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.estatusmandamiento.ActualizarEstatusMandamientoJudicial")
    @WebMethod
    @ResponseWrapper(localName = "actualizarEstatusMandamientoJudicialResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.estatusmandamiento.ActualizarEstatusMandamientoJudicialResponse")
    public java.lang.Boolean actualizarEstatusMandamientoJudicial(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.estatusmandamiento.MandamientoWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
