package mx.gob.segob.nsjp.ws.cliente.avidohdelictivo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:38.079-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "RecibirAvisoHDelictivoExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/RecibirAvisoHDelictivoExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class RecibirAvisoHDelictivoExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RecibirAvisoHDelictivoExporterImplService");
    public final static QName RecibirAvisoHDelictivoExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RecibirAvisoHDelictivoExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/RecibirAvisoHDelictivoExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RecibirAvisoHDelictivoExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/RecibirAvisoHDelictivoExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RecibirAvisoHDelictivoExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RecibirAvisoHDelictivoExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecibirAvisoHDelictivoExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RecibirAvisoHDelictivoExporter
     */
    @WebEndpoint(name = "RecibirAvisoHDelictivoExporterImplPort")
    public RecibirAvisoHDelictivoExporter getRecibirAvisoHDelictivoExporterImplPort() {
        return super.getPort(RecibirAvisoHDelictivoExporterImplPort, RecibirAvisoHDelictivoExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecibirAvisoHDelictivoExporter
     */
    @WebEndpoint(name = "RecibirAvisoHDelictivoExporterImplPort")
    public RecibirAvisoHDelictivoExporter getRecibirAvisoHDelictivoExporterImplPort(WebServiceFeature... features) {
        return super.getPort(RecibirAvisoHDelictivoExporterImplPort, RecibirAvisoHDelictivoExporter.class, features);
    }

}
