package mx.gob.segob.nsjp.ws.cliente.avidohdelictivo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:38.064-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "RecibirAvisoHDelictivoExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface RecibirAvisoHDelictivoExporter {

    @Action(input = "http://ws.service.nsjp.segob.gob.mx/RecibirAvisoHDelictivoExporter/recibirAvisoHDelictivoServiceRequest", output = "http://ws.service.nsjp.segob.gob.mx/RecibirAvisoHDelictivoExporter/recibirAvisoHDelictivoServiceResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/RecibirAvisoHDelictivoExporter/recibirAvisoHDelictivoService/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "recibirAvisoHDelictivoService", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.avidohdelictivo.RecibirAvisoHDelictivoService")
    @WebMethod
    @ResponseWrapper(localName = "recibirAvisoHDelictivoServiceResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.avidohdelictivo.RecibirAvisoHDelictivoServiceResponse")
    public void recibirAvisoHDelictivoService(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.avidohdelictivo.AvisoHechoDelictivoWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
