package mx.gob.segob.nsjp.ws.cliente.mandamiento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:44.296-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "RegistrarMandamientoExporterImplService", 
                  wsdlLocation = "http://localhost:49801/nsjp-web/RegistrarMandamientoExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class RegistrarMandamientoExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarMandamientoExporterImplService");
    public final static QName RegistrarMandamientoExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarMandamientoExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49801/nsjp-web/RegistrarMandamientoExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegistrarMandamientoExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49801/nsjp-web/RegistrarMandamientoExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegistrarMandamientoExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistrarMandamientoExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrarMandamientoExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RegistrarMandamientoExporter
     */
    @WebEndpoint(name = "RegistrarMandamientoExporterImplPort")
    public RegistrarMandamientoExporter getRegistrarMandamientoExporterImplPort() {
        return super.getPort(RegistrarMandamientoExporterImplPort, RegistrarMandamientoExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrarMandamientoExporter
     */
    @WebEndpoint(name = "RegistrarMandamientoExporterImplPort")
    public RegistrarMandamientoExporter getRegistrarMandamientoExporterImplPort(WebServiceFeature... features) {
        return super.getPort(RegistrarMandamientoExporterImplPort, RegistrarMandamientoExporter.class, features);
    }

}
