
package mx.gob.segob.nsjp.ws.cliente.consultartribunalespordistrito;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-08-16T13:45:19.914-05:00
 * Generated source version: 2.4.2
 * 
 */
public final class ConsultarTribunalesPorDistritoServiceExporter_ConsultarTribunalesPorDistritoServiceExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ConsultarTribunalesPorDistritoServiceExporterImplService");

    private ConsultarTribunalesPorDistritoServiceExporter_ConsultarTribunalesPorDistritoServiceExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConsultarTribunalesPorDistritoServiceExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ConsultarTribunalesPorDistritoServiceExporterImplService ss = new ConsultarTribunalesPorDistritoServiceExporterImplService(wsdlURL, SERVICE_NAME);
        ConsultarTribunalesPorDistritoServiceExporter port = ss.getConsultarTribunalesPorDistritoServiceExporterImplPort();  
        
        {
        System.out.println("Invoking consultarAgenciasPorDistrito...");
        java.lang.Long _consultarAgenciasPorDistrito_arg0 = null;
        try {
            java.util.List<mx.gob.segob.nsjp.ws.cliente.consultartribunalespordistrito.CatDiscriminanteWSDTO> _consultarAgenciasPorDistrito__return = port.consultarAgenciasPorDistrito(_consultarAgenciasPorDistrito_arg0);
            System.out.println("consultarAgenciasPorDistrito.result=" + _consultarAgenciasPorDistrito__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultarTribunalesPorDistrito...");
        java.lang.Long _consultarTribunalesPorDistrito_arg0 = null;
        try {
            java.util.List<mx.gob.segob.nsjp.ws.cliente.consultartribunalespordistrito.CatDiscriminanteWSDTO> _consultarTribunalesPorDistrito__return = port.consultarTribunalesPorDistrito(_consultarTribunalesPorDistrito_arg0);
            System.out.println("consultarTribunalesPorDistrito.result=" + _consultarTribunalesPorDistrito__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
